"""
SFT 数据补充模块 —— 在原有 30 条基础上新增 ~100 条
总计达到 ~130 条，覆盖 6 个类别
"""

# ========== 代码生成（原有10条 + 新增15条 = 25） ==========
CODE_GENERATION_EXTRA = [
    {
        "user": "用 Python 实现归并排序",
        "assistant": "```python\ndef merge_sort(arr):\n    if len(arr) <= 1:\n        return arr\n    mid = len(arr) // 2\n    left = merge_sort(arr[:mid])\n    right = merge_sort(arr[mid:])\n    return merge(left, right)\n\ndef merge(left, right):\n    result = []\n    i = j = 0\n    while i < len(left) and j < len(right):\n        if left[i] <= right[j]:\n            result.append(left[i])\n            i += 1\n        else:\n            result.append(right[j])\n            j += 1\n    result.extend(left[i:])\n    result.extend(right[j:])\n    return result\n```\n时间复杂度 O(n log n)，空间复杂度 O(n)。稳定排序。"
    },
    {
        "user": "用 Python 写一个 BFS（广度优先搜索）遍历二叉树",
        "assistant": "```python\nfrom collections import deque\n\nclass TreeNode:\n    def __init__(self, val=0, left=None, right=None):\n        self.val = val\n        self.left = left\n        self.right = right\n\ndef bfs(root):\n    if not root:\n        return []\n    result = []\n    queue = deque([root])\n    while queue:\n        node = queue.popleft()\n        result.append(node.val)\n        if node.left:\n            queue.append(node.left)\n        if node.right:\n            queue.append(node.right)\n    return result\n```\n使用 deque 实现队列，按层遍历二叉树。时间复杂度 O(n)，空间复杂度 O(n)。"
    },
    {
        "user": "用 Python 写一个简单的 REST API 客户端（使用 requests 库）",
        "assistant": "```python\nimport requests\nfrom typing import Optional, Dict, Any\n\nclass APIClient:\n    def __init__(self, base_url: str, token: Optional[str] = None):\n        self.base_url = base_url.rstrip('/')\n        self.session = requests.Session()\n        if token:\n            self.session.headers.update({\n                'Authorization': f'Bearer {token}',\n                'Content-Type': 'application/json'\n            })\n\n    def get(self, endpoint: str, params: Optional[Dict] = None) -> Dict[str, Any]:\n        resp = self.session.get(f'{self.base_url}/{endpoint.lstrip(\"/\")}', params=params)\n        resp.raise_for_status()\n        return resp.json()\n\n    def post(self, endpoint: str, data: Dict) -> Dict[str, Any]:\n        resp = self.session.post(f'{self.base_url}/{endpoint.lstrip(\"/\")}', json=data)\n        resp.raise_for_status()\n        return resp.json()\n\n    def put(self, endpoint: str, data: Dict) -> Dict[str, Any]:\n        resp = self.session.put(f'{self.base_url}/{endpoint.lstrip(\"/\")}', json=data)\n        resp.raise_for_status()\n        return resp.json()\n\n    def delete(self, endpoint: str) -> bool:\n        resp = self.session.delete(f'{self.base_url}/{endpoint.lstrip(\"/\")}')\n        return resp.status_code == 204\n```\n封装了 GET/POST/PUT/DELETE，使用 Session 复用连接，自动处理认证头。"
    },
    {
        "user": "用 Python 写一个正则提取 URL 中所有链接的函数",
        "assistant": "```python\nimport re\nfrom urllib.parse import urlparse\n\ndef extract_urls(text: str) -> list[str]:\n    pattern = r'https?://[^\\s<>\"{}|\\\\^`\\[\\]]+'\n    return re.findall(pattern, text)\n\n# 使用示例\ntext = \"\"\"\n访问 https://www.example.com 或 http://test.org/page?id=1\n参考文档：https://docs.python.org/3/library/re.html\n\"\"\"\nurls = extract_urls(text)\n# ['https://www.example.com', 'http://test.org/page?id=1', 'https://docs.python.org/3/library/re.html']\n```\n此正则匹配以 http:// 或 https:// 开头的 URL，排除常见的边界字符。"
    },
    {
        "user": "用 Java 写一个 Builder 模式的示例",
        "assistant": "```java\npublic class User {\n    private final String name;\n    private final int age;\n    private final String email;\n    private final String phone;\n\n    private User(Builder builder) {\n        this.name = builder.name;\n        this.age = builder.age;\n        this.email = builder.email;\n        this.phone = builder.phone;\n    }\n\n    public static class Builder {\n        private final String name;  // 必填\n        private int age;\n        private String email;\n        private String phone;\n\n        public Builder(String name) {\n            this.name = name;\n        }\n\n        public Builder age(int age) {\n            this.age = age;\n            return this;\n        }\n\n        public Builder email(String email) {\n            this.email = email;\n            return this;\n        }\n\n        public Builder phone(String phone) {\n            this.phone = phone;\n            return this;\n        }\n\n        public User build() {\n            return new User(this);\n        }\n    }\n}\n\n// 使用\nUser user = new User.Builder(\"张三\")\n    .age(25)\n    .email(\"zhangsan@example.com\")\n    .build();\n```\nBuilder 模式适合参数多且大部分可选的场景，代码可读性好，避免构造器参数过多。"
    },
    {
        "user": "用 Python 写一个简单的异步 HTTP 请求函数（使用 aiohttp）",
        "assistant": "```python\nimport aiohttp\nimport asyncio\nfrom typing import List, Dict, Any\n\nasync def fetch_json(session: aiohttp.ClientSession, url: str) -> Dict[str, Any]:\n    async with session.get(url) as resp:\n        resp.raise_for_status()\n        return await resp.json()\n\nasync def fetch_all(urls: List[str]) -> List[Dict[str, Any]]:\n    async with aiohttp.ClientSession() as session:\n        tasks = [fetch_json(session, url) for url in urls]\n        return await asyncio.gather(*tasks, return_exceptions=True)\n\n# 使用\n# results = asyncio.run(fetch_all([\n#     'https://api.example.com/data/1',\n#     'https://api.example.com/data/2',\n# ]))\n```\n`asyncio.gather` 并发执行多个请求，比顺序请求快数倍。`return_exceptions=True` 防止单个请求失败影响其他。"
    },
    {
        "user": "用 SQL 写一个查询：找出连续 3 天都登录的用户",
        "assistant": "```sql\nWITH user_logins AS (\n    SELECT DISTINCT user_id, login_date\n    FROM login_records\n),\nranked AS (\n    SELECT\n        user_id,\n        login_date,\n        ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY login_date) AS rn\n    FROM user_logins\n)\nSELECT DISTINCT user_id\nFROM ranked\nGROUP BY user_id, DATE_SUB(login_date, INTERVAL rn DAY)\nHAVING COUNT(*) >= 3;\n```\n核心思路：如果日期连续，`login_date - rn` 会得到相同的值，按这个值分组统计 >=3 即可。"
    },
    {
        "user": "用 Python 实现一个带过期时间的本地缓存",
        "assistant": "```python\nimport time\nfrom threading import Lock\n\nclass TTLCache:\n    def __init__(self, default_ttl: int = 60):\n        self._cache = {}\n        self._lock = Lock()\n        self.default_ttl = default_ttl\n\n    def get(self, key: str):\n        with self._lock:\n            if key in self._cache:\n                value, expire_at = self._cache[key]\n                if time.time() < expire_at:\n                    return value\n                del self._cache[key]\n        return None\n\n    def set(self, key: str, value, ttl: int = None):\n        ttl = ttl or self.default_ttl\n        with self._lock:\n            self._cache[key] = (value, time.time() + ttl)\n\n    def delete(self, key: str):\n        with self._lock:\n            self._cache.pop(key, None)\n\n    def clear_expired(self):\n        now = time.time()\n        with self._lock:\n            expired = [k for k, (_, exp) in self._cache.items() if now >= exp]\n            for k in expired:\n                del self._cache[k]\n```\n线程安全的 TTL 缓存实现，支持默认过期时间和自定义 TTL。适合缓存数据库查询结果等场景。"
    },
    {
        "user": "用 Java 写一个简单的线程池使用示例",
        "assistant": "```java\nimport java.util.concurrent.*;\nimport java.util.List;\n\npublic class ThreadPoolExample {\n    public static void main(String[] args) throws Exception {\n        // 创建固定大小线程池\n        ExecutorService executor = Executors.newFixedThreadPool(4);\n\n        // 提交多个任务\n        List<Future<Integer>> futures = List.of(\n            executor.submit(() -> compute(1)),\n            executor.submit(() -> compute(2)),\n            executor.submit(() -> compute(3))\n        );\n\n        // 收集结果\n        for (Future<Integer> future : futures) {\n            System.out.println(\"Result: \" + future.get(5, TimeUnit.SECONDS));\n        }\n\n        // 优雅关闭\n        executor.shutdown();\n        if (!executor.awaitTermination(10, TimeUnit.SECONDS)) {\n            executor.shutdownNow();\n        }\n    }\n\n    private static int compute(int input) {\n        return input * input;\n    }\n}\n```\n推荐使用 `ThreadPoolExecutor` 构造函数而非 `Executors` 工厂方法（后者可能隐藏风险如无界队列）。"
    },
    {
        "user": "用 Python 写一个配置文件解析器，支持 YAML 和 JSON",
        "assistant": "```python\nimport json\nimport os\nfrom typing import Dict, Any\n\ndef load_config(path: str) -> Dict[str, Any]:\n    \"\"\"根据扩展名自动选择解析方式\"\"\"\n    if not os.path.exists(path):\n        raise FileNotFoundError(f\"配置文件不存在: {path}\")\n\n    ext = os.path.splitext(path)[1].lower()\n\n    if ext in ('.yaml', '.yml'):\n        import yaml\n        with open(path, 'r', encoding='utf-8') as f:\n            return yaml.safe_load(f)\n\n    elif ext == '.json':\n        with open(path, 'r', encoding='utf-8') as f:\n            return json.load(f)\n\n    elif ext == '.toml':\n        import tomllib  # Python 3.11+\n        with open(path, 'rb') as f:\n            return tomllib.load(f)\n\n    else:\n        raise ValueError(f\"不支持的配置格式: {ext}\")\n```\n自动识别文件扩展名，支持 YAML/JSON/TOML 三种常见配置格式。"
    },
    {
        "user": "用 JavaScript 写一个防抖（debounce）函数",
        "assistant": "```javascript\nfunction debounce(func, delay) {\n    let timeoutId;\n    return function(...args) {\n        clearTimeout(timeoutId);\n        timeoutId = setTimeout(() => {\n            func.apply(this, args);\n        }, delay);\n    };\n}\n\n// 使用示例：搜索框输入防抖\nconst searchInput = document.getElementById('search');\nsearchInput.addEventListener('input', debounce(async (e) => {\n    const results = await fetch(`/api/search?q=${e.target.value}`);\n    renderResults(await results.json());\n}, 300));\n```\n防抖函数：在连续触发时只执行最后一次。适合搜索建议、窗口 resize 等高频事件。"
    },
    {
        "user": "用 Python 写一个支持分页的数据库查询辅助函数",
        "assistant": "```python\nfrom typing import List, Tuple, Optional\n\ndef paginate(\n    query: str,\n    page: int = 1,\n    page_size: int = 20,\n    order_by: Optional[str] = None\n) -> Tuple[str, dict]:\n    \"\"\"生成分页 SQL 和参数字典\"\"\"\n    if page < 1:\n        page = 1\n    if page_size < 1:\n        page_size = 20\n    if page_size > 100:\n        page_size = 100  # 限制最大页大小\n\n    offset = (page - 1) * page_size\n\n    sql = query.rstrip(';').strip()\n    if order_by:\n        sql += f' ORDER BY {order_by}'\n    sql += f' LIMIT {page_size} OFFSET {offset}'\n\n    meta = {\n        'page': page,\n        'page_size': page_size,\n        'offset': offset,\n    }\n    return sql, meta\n```\n自动计算 OFFSET，限制页大小防止大查询，返回 SQL 和分页元信息。"
    },
    {
        "user": "写一个 Bash 脚本，用于批量重命名文件（添加日期前缀）",
        "assistant": "```bash\n#!/bin/bash\n# 批量给文件添加日期前缀\n\nDATE=$(date +%Y%m%d)\nCOUNT=0\n\nfor file in \"$@\"; do\n    if [ -f \"$file\" ]; then\n        dir=$(dirname \"$file\")\n        base=$(basename \"$file\")\n        newname=\"${dir}/${DATE}_${base}\"\n        mv \"$file\" \"$newname\"\n        echo \"重命名: $file → $newname\"\n        ((COUNT++))\n    fi\ndone\n\necho \"共重命名 $COUNT 个文件\"\n```\n\n使用方法：\n```bash\nchmod +x rename.sh\n./rename.sh *.txt\n```\n脚本遍历所有参数，为每个文件在当前日期前加前缀。"
    },
    {
        "user": "用 Python 实现一个简单的观察者模式（Observer Pattern）",
        "assistant": "```python\nfrom abc import ABC, abstractmethod\nfrom typing import List\n\nclass Observer(ABC):\n    @abstractmethod\n    def update(self, message: str) -> None:\n        pass\n\nclass Subject:\n    def __init__(self):\n        self._observers: List[Observer] = []\n\n    def attach(self, observer: Observer):\n        self._observers.append(observer)\n\n    def detach(self, observer: Observer):\n        self._observers.remove(observer)\n\n    def notify(self, message: str):\n        for observer in self._observers:\n            observer.update(message)\n\n# 具体观察者\nclass EmailNotifier(Observer):\n    def update(self, message: str):\n        print(f\"[邮件通知] {message}\")\n\nclass SMSNotifier(Observer):\n    def update(self, message: str):\n        print(f\"[短信通知] {message}\")\n\n# 使用\nsubject = Subject()\nsubject.attach(EmailNotifier())\nsubject.attach(SMSNotifier())\nsubject.notify(\"订单已发货\")\n```\n观察者模式实现了一对多的依赖关系，当 Subject 状态变化时所有 Observer 自动收到通知。"
    },
    {
        "user": "用 Go 写一个简单的 HTTP 服务器",
        "assistant": "```go\npackage main\n\nimport (\n    \"encoding/json\"\n    \"log\"\n    \"net/http\"\n)\n\ntype Response struct {\n    Message string `json:\"message\"`\n    Status  int    `json:\"status\"`\n}\n\nfunc helloHandler(w http.ResponseWriter, r *http.Request) {\n    w.Header().Set(\"Content-Type\", \"application/json\")\n    resp := Response{Message: \"Hello, World!\", Status: 200}\n    json.NewEncoder(w).Encode(resp)\n}\n\nfunc main() {\n    http.HandleFunc(\"/api/hello\", helloHandler)\n    log.Println(\"Server starting on :8080\")\n    log.Fatal(http.ListenAndServe(\":8080\", nil))\n}\n```\nGo 标准库自带 HTTP 服务器，`net/http` 包即可快速构建 REST API。"
    },
]

# ========== 代码解释（原有6条 + 新增14条 = 20） ==========
CODE_EXPLANATION_EXTRA = [
    {
        "user": "解释 Python 中 `yield from` 的作用",
        "assistant": "`yield from` 是 Python 3.3+ 引入的语法，用于委托生成器。\n\n**作用**：\n1. **简化嵌套生成器**：将子生成器的值直接 yield 出去\n2. **双向通道**：send()/throw()/close() 会透传给子生成器\n3. **自动迭代可迭代对象**\n\n```python\n# 不使用 yield from\ndef flatten(nested):\n    for sublist in nested:\n        for item in sublist:\n            yield item\n\n# 使用 yield from\ndef flatten(nested):\n    for sublist in nested:\n        yield from sublist  # 委托给 sublist 的迭代器\n\n# 使用\ndata = [[1, 2], [3, 4], [5]]\nprint(list(flatten(data)))  # [1, 2, 3, 4, 5]\n```\n\n`yield from` 的本质是将调用方和子生成器之间建立直接通道，消除中间代理代码。"
    },
    {
        "user": "解释 Python 中 `__slots__` 的作用和适用场景",
        "assistant": "`__slots__` 是 Python 类的特殊属性，用于**限制实例属性集合**并**节省内存**。\n\n**原理**：\n- 普通类使用 `__dict__` 存储属性（字典开销 ~1KB/实例）\n- `__slots__` 用固定大小的数组存储属性，消除 `__dict__`\n\n```python\nclass Point:\n    __slots__ = ('x', 'y')\n\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\np = Point(1, 2)\np.z = 3  # AttributeError: 'Point' object has no attribute 'z'\n```\n\n**优点**：\n- 内存节省 40-50%（大量实例时显著）\n- 属性访问更快（数组索引 vs 字典查找）\n- 防止意外添加属性\n\n**注意**：\n- 不能动态添加新属性\n- 子类需重新声明 `__slots__`\n- 不适合需要 `__dict__` 的库（如 pickle 某些场景）"
    },
    {
        "user": "解释 Java 中 `transient` 关键字的作用",
        "assistant": "`transient` 关键字用于标记**不需要序列化的字段**。\n\n```java\npublic class User implements Serializable {\n    private String username;\n    private transient String password;  // 不会被序列化\n    private transient int cachedHash;    // 缓存值不需要持久化\n\n    // password 需要特殊处理\n    private void writeObject(ObjectOutputStream out) throws IOException {\n        out.defaultWriteObject();\n        out.writeObject(encrypt(password));  // 手动序列化加密后的密码\n    }\n\n    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {\n        in.defaultReadObject();\n        this.password = decrypt((String) in.readObject());\n    }\n}\n```\n\n**典型场景**：\n1. 敏感信息（密码、Token）\n2. 派生字段/缓存值（可从其他字段计算出）\n3. 不可序列化的对象引用（如数据库连接）\n\n**注意**：`transient` 字段反序列化后为 null/0/false。如需自定义可重写 `writeObject`/`readObject`。"
    },
    {
        "user": "解释 Docker 中 COPY 和 ADD 指令的区别",
        "assistant": "Dockerfile 中 `COPY` 和 `ADD` 都用于将文件复制到镜像，但有重要区别：\n\n| 特性 | COPY | ADD |\n|------|------|-----|\n| 复制本地文件 | ✅ | ✅ |\n| 自动解压 tar | ❌ | ✅ |\n| 远程 URL 下载 | ❌ | ✅（不推荐） |\n| 推荐程度 | ✅ 推荐 | ⚠️ 仅在需要解压时 |\n\n```dockerfile\n# COPY - 简单文件复制\nCOPY ./app /app\nCOPY requirements.txt /app/\n\n# ADD - 自动解压 tar.gz\nADD ./archive.tar.gz /app/  # 自动解压到 /app/\n\n# 不推荐用 ADD 做远程下载（没有清理机制）\n# ADD https://example.com/file.tar.gz /app/  # 不会被解压\n```\n\n**最佳实践**：\n- 默认使用 `COPY`（明确、简单）\n- 仅在需要自动解压本地 tar 文件时用 `ADD`\n- 远程下载用 `RUN curl` 或 `RUN wget`（可清理缓存）"
    },
    {
        "user": "解释 Git rebase 和 merge 的区别",
        "assistant": "**merge** 和 **rebase** 都是合并分支的方法，但处理方式不同：\n\n**Merge（合并）**：\n```\n    A---B---C feature\n   /         \\\nD---E---F---G---H main (H 是合并提交)\n```\n- 保留完整分支历史\n- 创建一个新的合并提交\n- 非线性历史但完整\n\n**Rebase（变基）**：\n```\n           A'--B'--C' feature（重放到 main 最新提交上）\n          /\nD---E---F---G main\n```\n- 将 feature 分支的提交\"移植\"到 main 顶端\n- 历史变成一条直线\n- 提交哈希会改变（A→A', B→B', C→C'）\n\n**选择指南**：\n- ✅ rebase：个人分支、保持线性历史\n- ✅ merge：公共分支、保留完整上下文\n- ❌ 不要对已推送的公共分支 rebase（会影响他人）"
    },
    {
        "user": "解释这段 Python 代码的输出和原理：\n\nfrom functools import lru_cache\n\n@lru_cache(maxsize=128)\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n-1) + fib(n-2)\n\nprint(fib(100))",
        "assistant": "这段代码使用 `@lru_cache` 装饰器实现了**带记忆化的斐波那契**计算。\n\n**原理**：\n- `lru_cache`（Least Recently Used Cache）自动缓存函数返回值\n- 参数 `maxsize=128` 表示最多缓存 128 个结果\n- 首次调用 `fib(100)` 时，递归计算并缓存所有中间结果\n- 后续相同参数的调用直接返回缓存值\n\n**性能对比**：\n- 无缓存：O(2ⁿ) → `fib(100)` 需要 ~10³⁰ 次调用（永远算不完）\n- 有缓存：O(n) → `fib(100)` 只需 101 次调用（毫秒级完成）\n\n**输出**：`354224848179261915075`（第 100 个斐波那契数）\n\n**注意**：`lru_cache` 要求函数参数必须是可哈希的（不能传 list/dict 等可变对象）。"
    },
    {
        "user": "解释 Java 中 `CompletableFuture` 的作用和常用方法",
        "assistant": "`CompletableFuture` 是 Java 8 引入的异步编程工具，支持组合多个异步操作。\n\n**核心方法**：\n\n```java\n// 1. 创建\nCompletableFuture<String> future = CompletableFuture.supplyAsync(() -> {\n    return fetchData();  // 在 ForkJoinPool 线程中执行\n});\n\n// 2. 转换（类似 map）\nCompletableFuture<Integer> lengthFuture = future.thenApply(String::length);\n\n// 3. 消费（类似 forEach）\nfuture.thenAccept(result -> System.out.println(\"Result: \" + result));\n\n// 4. 组合\nCompletableFuture<String> combined = future\n    .thenCompose(data -> CompletableFuture.supplyAsync(() -> process(data)));\n\n// 5. 并行执行\nCompletableFuture<String> f1 = CompletableFuture.supplyAsync(() -> query1());\nCompletableFuture<String> f2 = CompletableFuture.supplyAsync(() -> query2());\nCompletableFuture<String> result = f1.thenCombine(f2, (r1, r2) -> r1 + r2);\n\n// 6. 异常处理\nfuture.exceptionally(ex -> {\n    log.error(\"Failed\", ex);\n    return \"fallback\";\n});\n\n// 7. 等待完成\nString value = future.get(5, TimeUnit.SECONDS);\n```\n\n相比 Future，CompletableFuture 支持回调非阻塞、链式组合、异常处理，是现代 Java 异步编程的标配。"
    },
    {
        "user": "解释 RESTful API 设计中的幂等性概念",
        "assistant": "**幂等性（Idempotency）**：同一个操作执行一次和执行多次，对系统状态的影响相同。\n\n**HTTP 方法的幂等性**：\n\n| 方法 | 幂等 | 说明 |\n|------|------|------|\n| GET | ✅ | 读取操作，不影响资源状态 |\n| PUT | ✅ | 全量更新，多次执行结果一致 |\n| DELETE | ✅ | 第一次删除成功，后续返回 404 但效果相同 |\n| HEAD | ✅ | 同 GET，只返回头信息 |\n| POST | ❌ | 创建资源，多次执行会创建多个 |\n| PATCH | ⚠️ | 取决于实现，增量更新可能不幂等 |\n\n**为什么重要**：\n1. 网络重试安全：超时后可以安全地重试幂等请求\n2. 支付系统：防止重复扣款\n\n**实现幂等的常见方式**：\n- 客户端生成唯一 idempotency key\n- 服务端用 key 去重\n- `PUT /orders/{id}` 用资源 ID（幂等）代替 `POST /orders`（不幂等）"
    },
    {
        "user": "解释 Python 的 `async/await` 工作原理和事件循环",
        "assistant": "`async/await` 是 Python 3.5+ 的协程语法，基于**事件循环（Event Loop）**实现异步编程。\n\n**核心概念**：\n\n1. **协程（Coroutine）**：`async def` 定义的函数，返回协程对象\n2. **事件循环**：调度协程执行，管理 I/O 等待\n3. **Future/Task**：对协程的包装，追踪执行状态\n\n```python\nimport asyncio\n\nasync def fetch(url):\n    print(f\"开始请求 {url}\")\n    await asyncio.sleep(1)  # 模拟 I/O 等待\n    print(f\"完成请求 {url}\")\n    return f\"{url} 的数据\"\n\nasync def main():\n    # 并发执行\n    results = await asyncio.gather(\n        fetch(\"url1\"),\n        fetch(\"url2\"),\n        fetch(\"url3\"),\n    )\n    print(results)\n\nasyncio.run(main())\n```\n\n**关键点**：\n- `await` 挂起当前协程，事件循环切换到其他协程\n- 多个协程可以\"并发\"执行（在 I/O 等待时切换）\n- 不是真正的并行（单个线程），但适合 I/O 密集型任务\n- CPU 密集任务应使用 `loop.run_in_executor()` 放到线程池"
    },
    {
        "user": "解释 SQL 中 JOIN 的类型和区别：INNER JOIN vs LEFT JOIN vs RIGHT JOIN vs FULL JOIN",
        "assistant": "SQL JOIN 用于关联两个或多个表的行：\n\n**INNER JOIN（内连接）**：\n- 返回两表匹配的行\n- 不匹配的行会被丢弃\n```sql\nSELECT * FROM orders o\nINNER JOIN customers c ON o.customer_id = c.id;\n-- 只返回有对应客户的订单\n```\n\n**LEFT JOIN（左外连接）**：\n- 返回左表所有行 + 右表匹配行\n- 右表无匹配的，用 NULL 填充\n```sql\nSELECT * FROM orders o\nLEFT JOIN customers c ON o.customer_id = c.id;\n-- 返回所有订单，即使客户不存在\n```\n\n**RIGHT JOIN（右外连接）**：\n- 返回右表所有行 + 左表匹配行\n- 等价于调换表顺序的 LEFT JOIN\n\n**FULL JOIN（全外连接）**：\n- 返回两表所有行\n- 不匹配的一方用 NULL 填充\n```sql\nSELECT * FROM orders o\nFULL JOIN customers c ON o.customer_id = c.id;\n-- 返回所有订单和所有客户\n```\n\n**记忆技巧**：LEFT/RIGHT 指的是\"保留哪边表的所有行\"。"
    },
    {
        "user": "解释什么是 CORS（跨域资源共享）以及如何解决跨域问题",
        "assistant": "**CORS（Cross-Origin Resource Sharing）** 是浏览器的安全机制，用于控制不同源之间的 HTTP 请求。\n\n**同源策略**：协议 + 域名 + 端口完全相同才算同源。\n- `https://a.com:443` 和 `https://a.com:444` → 不同源\n- `https://a.com` 和 `http://a.com` → 不同源（协议不同）\n\n**关键响应头**：\n```\nAccess-Control-Allow-Origin: https://frontend.com\nAccess-Control-Allow-Methods: GET, POST, PUT, DELETE\nAccess-Control-Allow-Headers: Content-Type, Authorization\nAccess-Control-Allow-Credentials: true\nAccess-Control-Max-Age: 3600  # 预检请求缓存时间\n```\n\n**解决方式**：\n\n1. **SpringBoot**：\n```java\n@Configuration\npublic class CorsConfig implements WebMvcConfigurer {\n    @Override\n    public void addCorsMappings(CorsRegistry registry) {\n        registry.addMapping(\"/api/**\")\n                .allowedOrigins(\"https://frontend.com\")\n                .allowedMethods(\"GET\", \"POST\", \"PUT\", \"DELETE\")\n                .allowCredentials(true);\n    }\n}\n```\n\n2. **Nginx 反向代理**（推荐生产环境）：\n```nginx\nlocation /api/ {\n    proxy_pass http://backend:8080/;\n    add_header Access-Control-Allow-Origin $http_origin;\n}\n```\n\n**注意**：不要在生产环境使用 `Access-Control-Allow-Origin: *`。"
    },
    {
        "user": "解释 Python 中 `dataclass` 装饰器的作用",
        "assistant": "`@dataclass` 是 Python 3.7+ 引入的，用于自动生成 `__init__`、`__repr__`、`__eq__` 等特殊方法。\n\n```python\nfrom dataclasses import dataclass, field\nfrom typing import List\n\n@dataclass\nclass Product:\n    name: str\n    price: float\n    tags: List[str] = field(default_factory=list)  # 可变默认值必须用 default_factory\n    in_stock: bool = True\n\n# 自动生成的方法：\np = Product(\"Widget\", 19.99, tags=[\"electronics\"])\nprint(p)  # Product(name='Widget', price=19.99, tags=['electronics'], in_stock=True)\n\np2 = Product(\"Widget\", 19.99)\nprint(p == p2)  # True (按值比较)\n```\n\n**常用参数**：\n```python\n@dataclass(frozen=True)   # 不可变（类似 namedtuple）\nclass Point:\n    x: float\n    y: float\n\n@dataclass(order=True)    # 生成 < <= > >= 比较方法\nclass RankedItem:\n    score: int\n    name: str\n```\n\n相比普通类减少 80% 的样板代码。不适合需要复杂 `__init__` 逻辑的类。"
    },
    {
        "user": "解释 JWT（JSON Web Token）的结构和工作原理",
        "assistant": "**JWT** 是一种用于身份认证的紧凑令牌格式，由三部分组成（用 `.` 分隔）：\n\n```\nHeader.Payload.Signature\neyJhbGc... .eyJzdWI... .SflKxw...\n```\n\n**1. Header（头部）**：\n```json\n{\n  \"alg\": \"HS256\",\n  \"typ\": \"JWT\"\n}\n```\n\n**2. Payload（载荷）**：\n```json\n{\n  \"sub\": \"1234567890\",    // 用户ID\n  \"name\": \"张三\",\n  \"iat\": 1516239022,      // 签发时间\n  \"exp\": 1516242622       // 过期时间\n}\n```\n\n**3. Signature（签名）**：\n```\nHMACSHA256(base64UrlEncode(header) + \".\" + base64UrlEncode(payload), secret)\n```\n\n**认证流程**：\n1. 用户登录成功 → 服务端生成 JWT 返回\n2. 客户端存储 JWT（localStorage/Cookie）\n3. 后续请求携带 `Authorization: Bearer <token>`\n4. 服务端验证签名 → 信任 Payload 中的用户信息\n\n**优点**：无状态、跨域友好、适合微服务\n**缺点**：无法服务端主动失效、Payload 仅 Base64 编码（不加密，勿放敏感数据）"
    },
    {
        "user": "解释 Linux 中硬链接和软链接（符号链接）的区别",
        "assistant": "**硬链接（Hard Link）**：\n- 多个文件名指向同一个 inode\n- `ln file.txt hardlink.txt`\n- 删除原文件不影响硬链接（引用计数 > 0 即保留数据）\n- 不能跨文件系统\n- 不能链接目录（防止循环）\n\n**软链接（Symbolic Link）**：\n- 指向文件路径的快捷方式\n- `ln -s /original/path/file.txt symlink.txt`\n- 删除原文件 → 软链接失效（悬空链接）\n- 可以跨文件系统\n- 可以链接目录\n\n```bash\n# 创建硬链接\nln /data/file.txt /backup/file.txt\n\n# 创建软链接\nln -s /usr/local/bin/python3 /usr/bin/python\n\n# 查看 inode\nls -li file.txt hardlink.txt  # inode 号相同（硬链接）\nls -li symlink.txt            # inode 号不同，显示 -> 原始路径\n```\n\n**选择**：数据备份用硬链接（不占额外空间），路径重定向用软链接（灵活）。"
    },
]

# ========== Bug修复（原有5条 + 新增17条 = 22） ==========
BUG_FIX_EXTRA = [
    {
        "user": "这段 Python 代码有什么问题？\n\ndef get_user(id):\n    user = db.query(f\"SELECT * FROM users WHERE id = {id}\")\n    return user",
        "assistant": "**问题**：SQL 注入漏洞。直接将用户输入拼接进 SQL 语句。\n\n如果 `id = \"1; DROP TABLE users; --\"`，会执行：\n```sql\nSELECT * FROM users WHERE id = 1; DROP TABLE users; --\n```\n\n**修复**：使用参数化查询\n```python\ndef get_user(id):\n    user = db.query(\"SELECT * FROM users WHERE id = ?\", (id,))\n    return user\n\n# 或者使用 ORM\nfrom sqlalchemy import select\nuser = session.execute(select(User).where(User.id == id)).scalar()\n```\n\n**关键原则**：永远不要拼接用户输入到 SQL 中，始终使用参数化查询或 ORM。"
    },
    {
        "user": "这段 Java 代码会导致内存泄漏吗？为什么？\n\npublic class Cache {\n    private static final Map<String, byte[]> cache = new HashMap<>();\n\n    public static void put(String key, byte[] data) {\n        cache.put(key, data);\n    }\n\n    public static byte[] get(String key) {\n        return cache.get(key);\n    }\n}",
        "assistant": "**是的，会导致严重的内存泄漏。**\n\n**原因**：\n1. `static final HashMap` 生命周期与 JVM 一样长\n2. `put()` 只会添加，没有删除机制\n3. `byte[]` 可能很大（如图片、文件数据）\n4. 随着时间推移，缓存无限增长直到 OOM\n\n**修复方案 1：使用 Guava Cache**\n```java\nprivate static final Cache<String, byte[]> cache = CacheBuilder.newBuilder()\n    .maximumSize(1000)\n    .expireAfterWrite(10, TimeUnit.MINUTES)\n    .build();\n```\n\n**修复方案 2：使用 Caffeine（推荐）**\n```java\nprivate static final Cache<String, byte[]> cache = Caffeine.newBuilder()\n    .maximumWeight(100 * 1024 * 1024)  // 最大 100MB\n    .expireAfterAccess(30, TimeUnit.MINUTES)\n    .build();\n```\n\n**修复方案 3：手动实现 LRU**\n```java\nprivate static final Map<String, byte[]> cache =\n    new LinkedHashMap<>(16, 0.75f, true) {\n        @Override\n        protected boolean removeEldestEntry(Map.Entry<String, byte[]> eldest) {\n            return size() > 1000;\n        }\n    };\n```"
    },
    {
        "user": "这段代码有什么并发问题？\n\npublic class Counter {\n    private int count = 0;\n\n    public void increment() {\n        count++;\n    }\n\n    public int getCount() {\n        return count;\n    }\n}",
        "assistant": "**问题**：`count++` 不是原子操作，多线程并发调用会导致计数丢失。\n\n`count++` 实际分三步：\n1. 读取 count 值\n2. 计算 count + 1\n3. 写入新值\n\n两个线程同时执行时可能都读到相同的旧值，导致一次递增丢失。\n\n**修复方案 1：synchronized**\n```java\npublic synchronized void increment() {\n    count++;\n}\n```\n\n**修复方案 2：AtomicInteger（推荐）**\n```java\nimport java.util.concurrent.atomic.AtomicInteger;\n\npublic class Counter {\n    private final AtomicInteger count = new AtomicInteger(0);\n\n    public void increment() {\n        count.incrementAndGet();  // CAS 底层实现\n    }\n\n    public int getCount() {\n        return count.get();\n    }\n}\n```\n\n**修复方案 3：LongAdder（高并发场景）**\n```java\nprivate final LongAdder count = new LongAdder();\npublic void increment() { count.increment(); }\n```\n\nAtomicInteger 适合中等并发，LongAdder 适合极高并发（分段计数减少竞争）。"
    },
    {
        "user": "这段 Python 代码打开文件有什么问题？\n\nf = open(\"data.txt\", \"r\")\ndata = f.read()\nprocess(data)\nf.close()",
        "assistant": "**问题**：如果 `f.read()` 或 `process(data)` 抛出异常，`f.close()` 不会执行，导致文件句柄泄漏。\n\n长时间运行的程序可能耗尽文件描述符。\n\n**修复：使用 with 语句**\n```python\nwith open(\"data.txt\", \"r\") as f:\n    data = f.read()\n    process(data)\n# 无论是否异常，文件都会被关闭\n```\n\n`with` 语句确保 `__exit__` 方法始终被调用，即使发生异常也会关闭文件。\n\n**同样适用于其他资源**：\n```python\n# 数据库连接\nwith get_db_connection() as conn:\n    cursor = conn.execute(\"SELECT ...\")\n\n# 网络连接\nwith socket.create_connection((host, port)) as sock:\n    sock.sendall(data)\n\n# 锁\nwith threading.Lock():\n    shared_resource.modify()\n```\n\n**原则**：任何需要手动释放的资源，都应该使用上下文管理器。"
    },
    {
        "user": "这段 Python 列表拷贝代码有什么问题？\n\ndef modify_list(items):\n    copy = items\n    copy.append(100)\n    return items",
        "assistant": "**问题**：`copy = items` 不会创建新列表，只是给同一个对象起了个别名。对 `copy` 的修改会直接影响 `items`。\n\n```python\noriginal = [1, 2, 3]\nresult = modify_list(original)\nprint(original)  # [1, 2, 3, 100] ← 被意外修改！\nprint(result)    # [1, 2, 3, 100]\nprint(original is result)  # True ← 同一个对象！\n```\n\n**修复**：\n```python\ndef modify_list(items):\n    copy = items.copy()      # 浅拷贝\n    # 或 copy = items[:]\n    # 或 copy = list(items)\n    # 或 import copy; copy = copy.copy(items)\n    copy.append(100)\n    return copy\n\noriginal = [1, 2, 3]\nresult = modify_list(original)\nprint(original)  # [1, 2, 3] ← 保持不变\nprint(result)    # [1, 2, 3, 100]\n```\n\n**注意**：列表的 `.copy()` 是浅拷贝。如果列表中包含可变对象（如嵌套列表），需要用 `copy.deepcopy()`。"
    },
    {
        "user": "这段 Java 代码的异常处理有什么问题？\n\ntry {\n    String data = readFile(\"config.json\");\n    User user = parseUser(data);\n    saveUser(user);\n} catch (Exception e) {\n    // 忽略异常\n}",
        "assistant": "**问题**：\n\n1. **吞掉异常（Swallowing Exceptions）**：捕获了所有异常但不做任何处理，问题被完全隐藏\n2. **捕获范围过大**：`catch (Exception e)` 捕获了所有异常类型，无法区分处理\n3. **丢失上下文**：不记录日志，排查问题无从下手\n\n**修复**：\n```java\ntry {\n    String data = readFile(\"config.json\");\n    User user = parseUser(data);\n    saveUser(user);\n} catch (FileNotFoundException e) {\n    log.error(\"配置文件不存在: {}\", e.getMessage());\n    throw new ConfigException(\"无法加载配置\", e);  // 包装后重新抛出\n} catch (JsonParseException e) {\n    log.error(\"JSON 格式错误: {}\", e.getMessage());\n    return new User();  // 返回默认值\n} catch (DataAccessException e) {\n    log.error(\"数据库保存失败\", e);\n    throw new ServiceException(\"用户保存失败，请稍后重试\", e);\n}\n```\n\n**原则**：\n- 只捕获知道如何处理的异常\n- 记录完整的堆栈信息\n- 考虑是重试、降级还是重新抛出"
    },
    {
        "user": "这段代码的浮点数比较有什么问题？\n\ndef calculate_total(items):\n    total = 0.0\n    for item in items:\n        total += item.price  # price 是 float\n    return total\n\nassert calculate_total([...]) == 0.30  # 可能失败！",
        "assistant": "**问题**：浮点数精度问题。二进制浮点数无法精确表示十进制小数。\n\n```python\n0.1 + 0.2 == 0.3  # False!\n0.1 + 0.2        # 0.30000000000000004\n```\n\n**修复方案 1：使用 Decimal（金额计算推荐）**\n```python\nfrom decimal import Decimal\n\ndef calculate_total(items):\n    total = Decimal('0')\n    for item in items:\n        total += Decimal(str(item.price))  # 从字符串构造避免浮点误差\n    return total\n```\n\n**修复方案 2：使用整数表示分**\n```python\ndef calculate_total(items):\n    total_cents = 0\n    for item in items:\n        total_cents += int(round(item.price * 100))\n    return total_cents / 100\n```\n\n**修复方案 3：使用 math.isclose 比较**\n```python\nimport math\nassert math.isclose(calculate_total([...]), 0.30, rel_tol=1e-9)\n```\n\n**金额处理铁律**：永远不要用 float 存储金额，用 Decimal 或整数（分）。"
    },
    {
        "user": "这段代码在什么情况下会出 IndexError？如何修复？\n\ndef get_first_and_last(items):\n    return items[0], items[-1]",
        "assistant": "**问题**：`items` 为空列表时，`items[0]` 会抛出 `IndexError: list index out of range`，`items[-1]` 同样。\n\n```python\nget_first_and_last([])  # IndexError!\n```\n\n**修复方案 1：返回默认值**\n```python\ndef get_first_and_last(items):\n    if not items:\n        return None, None\n    return items[0], items[-1]\n```\n\n**修复方案 2：使用切片（切片不会抛异常）**\n```python\ndef get_first_and_last(items):\n    first = items[0] if items else None\n    last = items[-1] if items else None\n    return first, last\n```\n\n**修复方案 3：Python 3.12+ 使用更优雅的写法**\n```python\ndef get_first_and_last(items):\n    match items:\n        case [first, *_, last]:\n            return first, last\n        case [single]:\n            return single, single\n        case []:\n            return None, None\n```\n\n**原则**：对外提供的 API 永远要防御性地处理边界情况（空列表、None 值等）。"
    },
    {
        "user": "这段代码在 Python 中有性能问题吗？\n\ndef find_users(names, user_list):\n    result = []\n    for name in names:\n        for user in user_list:\n            if user.name == name:\n                result.append(user)\n    return result\n\n# names 有 100 个，user_list 有 10000 个",
        "assistant": "**问题**：O(n × m) 时间复杂度，100 × 10000 = 1,000,000 次比较。\n\n**修复：用字典建立索引（O(n + m)）**\n```python\ndef find_users(names, user_list):\n    # 建立名字 → 用户的映射（O(m)）\n    user_map = {user.name: user for user in user_list}\n    # 查找（O(n)）\n    return [user_map[name] for name in names if name in user_map]\n```\n\n**性能对比**：\n- 原代码：1,000,000 次循环 → ~50ms\n- 优化后：10,100 次操作 → ~0.5ms\n- 快 100 倍\n\n**更通用的优化模式**：\n- 嵌套循环查找 → 先建哈希表（dict/set）再查找\n- 适用于 Python、Java、JS 等所有语言\n- 代价是 O(m) 额外空间"
    },
    {
        "user": "这段配置代码的安全问题是什么？\n\n# application.properties\nspring.datasource.password=admin123\njwt.secret=my-secret-key",
        "assistant": "**问题**：敏感信息硬编码在配置文件中，提交到 Git 后会永远留在历史记录。\n\n**风险**：\n- 代码仓库泄露 → 数据库密码泄露\n- JWT secret 泄露 → 攻击者可伪造任意 Token\n- 即使后续修改，Git 历史仍可查看\n\n**修复方案 1：环境变量**\n```properties\nspring.datasource.password=${DB_PASSWORD}\njwt.secret=${JWT_SECRET}\n```\n\n**修复方案 2：SpringBoot 外部配置**\n```bash\njava -jar app.jar --spring.datasource.password=xxx --jwt.secret=xxx\n```\n\n**修复方案 3：配置中心（生产环境）**\n```yaml\n# 使用 Vault / AWS Secrets Manager / 腾讯云凭据管理\nspring:\n  config:\n    import: vault://secret/application\n```\n\n**Git 处理**：\n```bash\n# 如果已经提交了敏感信息\ngit filter-branch --force --index-filter \\\n  \"git rm --cached --ignore-unmatch application.properties\" \\\n  --prune-empty --tag-name-filter cat -- --all\n```\n\n**原则**：所有密钥、密码、Token 都不能出现在代码仓库中。"
    },
    {
        "user": "这段 Python 正则匹配有什么问题？\n\ndef is_valid_email(email):\n    import re\n    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'\n    return bool(re.match(pattern, email))",
        "assistant": "**问题**：\n\n1. **正则不完整**：会拒绝有效的邮箱，如 `user+tag@domain.com`（已被匹配），但会拒绝包含中文域名的邮箱\n2. **更大的问题**：用正则完全验证邮箱是不可靠的做法\n3. **可能误拒**：有效的邮箱格式比你想象的复杂得多（引号、注释、IP 域名等）\n\n实际有效的邮箱示例：\n- `\"very.unusual.@.unusual.com\"@example.com` ✅\n- `user@[192.168.1.1]` ✅\n- `user@localhost` ✅（无 TLD 也是有效的）\n\n**修复**：\n```python\nimport re\n\ndef is_valid_email(email):\n    # 只做基本格式检查\n    if not email or '@' not in email:\n        return False\n    local, _, domain = email.rpartition('@')\n    return bool(local) and bool(domain) and '.' in domain\n    # 真正的验证：发送验证邮件！\n```\n\n**最佳实践**：\n1. 只做基础格式检查（是否有 @ 符号）\n2. 发送验证邮件确认\n3. 不要过度依赖正则做终极验证"
    },
    {
        "user": "这段 Python 代码的递归有什么问题？\n\ndef factorial(n):\n    return n * factorial(n - 1)",
        "assistant": "**问题**：\n\n1. **缺少基准条件（Base Case）**：会无限递归直到栈溢出\n2. **没有处理负数输入**\n\n```python\nfactorial(5)\n# RecursionError: maximum recursion depth exceeded\n```\n\n**修复**：\n```python\ndef factorial(n):\n    if n < 0:\n        raise ValueError(\"n must be non-negative\")\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n```\n\n**更好的实现（迭代，避免递归开销）**：\n```python\ndef factorial(n):\n    if n < 0:\n        raise ValueError(\"n must be non-negative\")\n    result = 1\n    for i in range(2, n + 1):\n        result *= i\n    return result\n\n# 或者用标准库\nimport math\nmath.factorial(100)  # 内部优化，支持大整数\n```\n\n**原则**：每个递归函数必须有明确的基准条件和收敛逻辑。"
    },
    {
        "user": "这段 Java 代码的字符串拼接有什么性能问题？\n\npublic String buildReport(List<String> items) {\n    String result = \"\";\n    for (String item : items) {\n        result += \"- \" + item + \"\\n\";\n    }\n    return result;\n}",
        "assistant": "**问题**：String 是不可变的，每次 `+=` 都创建新的 String 对象。\n\n- 100 个元素 → 创建 100 个中间 String 对象\n- 每次都复制之前的内容 → O(n²) 时间复杂度\n\n**修复：使用 StringBuilder**\n```java\npublic String buildReport(List<String> items) {\n    StringBuilder sb = new StringBuilder();\n    for (String item : items) {\n        sb.append(\"- \").append(item).append(\"\\n\");\n    }\n    return sb.toString();\n}\n\n// Java 8+ 更简洁的写法\npublic String buildReport(List<String> items) {\n    return items.stream()\n        .map(item -> \"- \" + item)\n        .collect(Collectors.joining(\"\\n\"));\n}\n```\n\n**性能对比**（10000 个元素）：\n- String `+=`：~500ms\n- StringBuilder：~1ms\n\n**原则**：循环中拼接字符串用 StringBuilder（Java）/ join（Python）/ 数组 join（JavaScript）。"
    },
    {
        "user": "这段 Python 代码的 with 语句使用正确吗？\n\ndef process_files(paths):\n    files = [open(p) for p in paths]\n    for f in files:\n        data = f.read()\n        process(data)\n    for f in files:\n        f.close()",
        "assistant": "**问题**：\n\n1. **资源泄漏风险**：如果 `open()` 或 `process(data)` 抛出异常，`f.close()` 不会执行\n2. **循环中的异常中断**：第一个文件处理失败后，所有文件都不会被关闭\n\n**修复**：\n```python\ndef process_files(paths):\n    for path in paths:\n        with open(path) as f:  # 每个文件独立 with\n            data = f.read()\n            process(data)\n```\n\n如果需要同时打开多个文件：\n```python\n# Python 3.10+\nwith (\n    open('input.txt') as infile,\n    open('output.txt', 'w') as outfile\n):\n    outfile.write(infile.read())\n\n# 或使用 contextlib.ExitStack\nfrom contextlib import ExitStack\n\nwith ExitStack() as stack:\n    files = [stack.enter_context(open(p)) for p in paths]\n    for f in files:\n        process(f.read())\n```\n\n**原则**：资源获取和释放应该绑定在一起，用 context manager 机制保证释放。"
    },
    {
        "user": "这段代码的时区处理有什么问题？\n\nfrom datetime import datetime\n\ndef format_time(timestamp):\n    dt = datetime.fromtimestamp(timestamp)\n    return dt.strftime('%Y-%m-%d %H:%M:%S')",
        "assistant": "**问题**：没有指定时区，默认使用系统本地时区。在不同服务器上结果可能不同。\n\n**风险**：\n- 开发机(UTC+8) 和服务器(UTC+0) 显示的时间不同\n- 国际化应用无法正确处理多时区\n- 跨时区数据对比混乱\n\n**修复**：\n```python\nfrom datetime import datetime, timezone, timedelta\n\n# 方案 1：始终使用 UTC\ndef format_time(timestamp):\n    dt = datetime.fromtimestamp(timestamp, tz=timezone.utc)\n    return dt.strftime('%Y-%m-%d %H:%M:%S UTC')\n\n# 方案 2：明确指定时区\ndef format_time(timestamp, tz_offset=8):\n    tz = timezone(timedelta(hours=tz_offset))\n    dt = datetime.fromtimestamp(timestamp, tz=tz)\n    return dt.strftime(f'%Y-%m-%d %H:%M:%S UTC{tz_offset:+d}')\n\n# 方案 3：使用 zoneinfo（Python 3.9+）\nfrom zoneinfo import ZoneInfo\n\ndef format_time(timestamp):\n    dt = datetime.fromtimestamp(timestamp, tz=ZoneInfo('Asia/Shanghai'))\n    return dt.strftime('%Y-%m-%d %H:%M:%S %Z')\n```\n\n**最佳实践**：数据库存 UTC，展示时转换到用户时区。"
    },
    {
        "user": "这段代码的 try-except 有什么逻辑问题？\n\ndef get_config(key):\n    try:\n        return config[key]\n    except KeyError:\n        return default_config[key]",
        "assistant": "**问题**：异常处理中又可能抛出相同的异常。如果 `key` 也不在 `default_config` 中，会抛出 `KeyError` 且不被捕获。\n\n```python\nget_config('missing_key')  # 如果 default_config 中也没有 → KeyError!\n```\n\n**修复**：\n```python\ndef get_config(key):\n    # 方案 1：链式默认值\n    return config.get(key, default_config.get(key))\n\n# 方案 2：多个后备配置\n# 方案 3：明确的默认值\ndef get_config(key):\n    return config.get(key, default_config.get(key, f\"默认{key}\"))\n\n# 方案 4：如果必须用 try-except，嵌套或分情况\ndef get_config(key):\n    try:\n        return config[key]\n    except KeyError:\n        try:\n            return default_config[key]\n        except KeyError:\n            raise ConfigError(f\"配置项 {key} 不存在于任何配置源中\")\n```\n\n**原则**：防御性编程，确保每一个可能失败的路径都有兜底处理。"
    },
    {
        "user": "这段多线程代码有什么问题？\n\nimport threading\n\nitems = []\n\ndef worker():\n    for i in range(1000):\n        items.append(i)\n\nthreads = [threading.Thread(target=worker) for _ in range(10)]\nfor t in threads:\n    t.start()\nfor t in threads:\n    t.join()\nprint(len(items))  # 可能不是 10000！",
        "assistant": "**问题**：`list.append()` 不是线程安全的操作。多个线程同时 append 可能导致数据竞争（data race）。\n\n虽然 Python 的 GIL 保证单个字节码操作是原子的，但 `append` 涉及多个步骤，在字节码层面可能被打断。实际测试中确实会出现元素丢失。\n\n**修复**：\n```python\nimport threading\n\nitems = []\nlock = threading.Lock()\n\ndef worker():\n    for i in range(1000):\n        with lock:\n            items.append(i)\n\nthreads = [threading.Thread(target=worker) for _ in range(10)]\nfor t in threads:\n    t.start()\nfor t in threads:\n    t.join()\nprint(len(items))  # 永远是 10000\n```\n\n**更好的方案**：用 `queue.Queue`（线程安全）\n```python\nfrom queue import Queue\n\nq = Queue()\ndef worker():\n    for i in range(1000):\n        q.put(i)\n\n# 最后从 q 中取出所有元素\nitems = list(q.queue)\n```"
    },
]

# ========== 代码优化（原有2条 + 新增14条 = 16） ==========
CODE_OPTIMIZATION_EXTRA = [
    {
        "user": "优化这段频繁创建对象的 Java 代码：\n\npublic String formatUser(User user) {\n    return \"User[id=\" + user.getId() + \", name=\" + user.getName() + \"]\";\n}",
        "assistant": "**问题**：每次调用创建多个中间 String 对象（通过 `+` 拼接）。\n\n**优化**：\n```java\n// 方案 1：使用 StringBuilder\npublic String formatUser(User user) {\n    return new StringBuilder()\n        .append(\"User[id=\")\n        .append(user.getId())\n        .append(\", name=\")\n        .append(user.getName())\n        .append(\"]\")\n        .toString();\n}\n\n// 方案 2：使用 String.format（可读性好，但性能略低于 StringBuilder）\npublic String formatUser(User user) {\n    return String.format(\"User[id=%d, name=%s]\", user.getId(), user.getName());\n}\n\n// 方案 3：Lombok @ToString（自动生成）\n@ToString\npublic class User {\n    ...\n}\n```\n\n如果调用不频繁，优先级：可读性 > 微优化。热路径（每秒上万次）用 StringBuilder。"
    },
    {
        "user": "优化这个数据库查询：一个页面需要加载用户列表 + 每个用户的最近订单，如何减少数据库查询次数？",
        "assistant": "**问题**：常见的 N+1 查询模式。\n\n**方案 1：JOIN 一次查询**\n```sql\nSELECT u.*, o.*\nFROM users u\nLEFT JOIN orders o ON o.user_id = u.id\n  AND o.created_at = (\n    SELECT MAX(created_at) FROM orders WHERE user_id = u.id\n  )\nWHERE u.status = 'active'\nORDER BY u.id;\n```\n\n**方案 2：窗口函数**\n```sql\nWITH latest_orders AS (\n    SELECT *,\n        ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY created_at DESC) AS rn\n    FROM orders\n)\nSELECT u.*, lo.*\nFROM users u\nLEFT JOIN latest_orders lo ON lo.user_id = u.id AND lo.rn = 1\nWHERE u.status = 'active';\n```\n\n**方案 3：批量查询（两步）**\n```python\n# 第一步：获取用户\nusers = User.query.filter_by(status='active').all()\nuser_ids = [u.id for u in users]\n\n# 第二步：批量获取订单（1 条 SQL）\norders = Order.query.filter(\n    Order.user_id.in_(user_ids),\n    Order.id.in_(\n        db.session.query(db.func.max(Order.id))\n        .filter(Order.user_id.in_(user_ids))\n        .group_by(Order.user_id)\n    )\n).all()\n```\n\n对比：N 个用户 → 从 N+1 次查询降为 1-2 次查询。"
    },
    {
        "user": "如何优化这段大量字符串判断的代码？\n\ndef get_content_type(ext):\n    if ext == 'html' or ext == 'htm':\n        return 'text/html'\n    elif ext == 'css':\n        return 'text/css'\n    elif ext == 'js':\n        return 'application/javascript'\n    elif ext == 'json':\n        return 'application/json'\n    elif ext == 'png':\n        return 'image/png'\n    # ... 20 多个 elif",
        "assistant": "**问题**：O(n) 查找，代码冗长。\n\n**优化：使用字典映射**\n```python\nMIME_TYPES = {\n    'html': 'text/html',\n    'htm': 'text/html',\n    'css': 'text/css',\n    'js': 'application/javascript',\n    'json': 'application/json',\n    'png': 'image/png',\n    'jpg': 'image/jpeg',\n    'jpeg': 'image/jpeg',\n    'gif': 'image/gif',\n    'svg': 'image/svg+xml',\n    'pdf': 'application/pdf',\n    'zip': 'application/zip',\n    'xml': 'application/xml',\n    'txt': 'text/plain',\n    'csv': 'text/csv',\n}\n\ndef get_content_type(ext):\n    return MIME_TYPES.get(ext.lower(), 'application/octet-stream')\n```\n\n**优点**：\n- O(1) 查找\n- 数据与逻辑分离\n- 易于维护和扩展\n- 可以放在配置文件中动态加载"
    },
    {
        "user": "优化这段 Python 代码：大文件逐行处理时内存占用过高\n\ndef process_file(path):\n    lines = open(path).readlines()  # 一次性加载所有行\n    results = []\n    for line in lines:\n        results.append(process(line))\n    return results",
        "assistant": "**优化**：\n```python\ndef process_file(path):\n    results = []\n    with open(path) as f:\n        for line in f:  # 逐行迭代，不一次性加载\n            results.append(process(line))\n    return results\n```\n\n对于超大文件（GB 级别），使用生成器避免内存爆炸：\n```python\ndef process_file(path):\n    with open(path) as f:\n        for line in f:  # 生成器：惰性求值\n            yield process(line)\n\n# 使用\nfor result in process_file('huge_file.txt'):\n    save_to_db(result)\n```\n\n**对比**：\n- 原代码：1GB 文件 → ~1GB 内存\n- 生成器方案：1GB 文件 → ~几KB 内存（仅当前行）\n\n**原理**：Python 文件对象本身就是迭代器，`for line in f` 逐行读取。"
    },
    {
        "user": "如何优化这个循环中重复计算的问题？\n\nfor item in items:\n    result.append(\n        math.sqrt(x**2 + y**2) * math.sin(theta) + len(items) * factor\n    )",
        "assistant": "**优化：将循环不变量提取到外部**\n```python\n# 循环中不变的计算 → 提取到循环外面\nn_items = len(items)\nsin_theta = math.sin(theta)\n\nfor item in items:\n    result.append(\n        math.sqrt(x**2 + y**2) * sin_theta + n_items * factor\n    )\n```\n\n如果 `x` 和 `y` 也是不变的：\n```python\ndistance = math.sqrt(x**2 + y**2)\nn_items = len(items)\nsin_theta = math.sin(theta)\n\nfor item in items:\n    result.append(distance * sin_theta + n_items * factor)\n```\n\n**编译器无法自动优化的原因**：\n- `len(items)` 可能因为副作用而改变（虽然这里是读操作）\n- `math.sin(theta)` 编译器不知道是否有副作用\n- Python 是动态语言，编译时优化空间有限"
    },
    {
        "user": "优化这个使用大量 if-else 逻辑的 Java 价格计算器",
        "assistant": "**问题**：if-else 链膨胀，扩展需修改类（违反开闭原则）。\n\n**优化：策略模式 + 工厂**\n```java\n// 策略接口\npublic interface PricingStrategy {\n    BigDecimal calculate(Order order);\n    boolean supports(String userType);\n}\n\n// 具体策略\n@Component\npublic class NormalPricing implements PricingStrategy {\n    public BigDecimal calculate(Order order) {\n        return order.getPrice();\n    }\n    public boolean supports(String userType) {\n        return \"normal\".equals(userType);\n    }\n}\n\n@Component\npublic class VipPricing implements PricingStrategy {\n    public BigDecimal calculate(Order order) {\n        return order.getPrice().multiply(new BigDecimal(\"0.9\"));\n    }\n    public boolean supports(String userType) {\n        return \"vip\".equals(userType);\n    }\n}\n\n// 工厂（自动发现所有策略）\n@Service\npublic class PricingService {\n    private final Map<String, PricingStrategy> strategies;\n\n    public PricingService(List<PricingStrategy> strategyList) {\n        this.strategies = strategyList.stream()\n            .collect(Collectors.toMap(\n                s -> s.getClass().getSimpleName(),\n                Function.identity()\n            ));\n    }\n\n    public BigDecimal calculatePrice(Order order, String userType) {\n        return strategies.values().stream()\n            .filter(s -> s.supports(userType))\n            .findFirst()\n            .map(s -> s.calculate(order))\n            .orElseThrow(() -> new IllegalArgumentException(\"Unknown user type: \" + userType));\n    }\n}\n```\n\n新增用户类型只需添加新的策略类，无需修改现有代码。"
    },
    {
        "user": "优化这个列表去重但保持顺序的 Python 代码：\n\nresult = []\nfor item in items:\n    if item not in result:  # O(n) 查找\n        result.append(item)",
        "assistant": "**问题**：`item not in result` 每次 O(k)，k 是 result 当前长度。总体 O(n²)。\n\n**优化**：\n```python\n# 方案 1：set + list（推荐）\ndef deduplicate(items):\n    seen = set()\n    result = []\n    for item in items:\n        if item not in seen:  # O(1) 查找\n            seen.add(item)\n            result.append(item)\n    return result\n\n# 方案 2：dict（Python 3.7+ 字典保序）\ndef deduplicate(items):\n    return list(dict.fromkeys(items))\n\n# 方案 3：保留首次出现的元素（带条件去重）\ndef deduplicate_by_key(items, key_func):\n    seen = set()\n    result = []\n    for item in items:\n        k = key_func(item)\n        if k not in seen:\n            seen.add(k)\n            result.append(item)\n    return result\n```\n\n**性能对比**（n=10000）：\n- 原代码：~0.5s\n- set 方案：~0.001s"
    },
    {
        "user": "如何优化 Python 中频繁的 JSON 序列化/反序列化？",
        "assistant": "**常见瓶颈和优化**：\n\n1. **使用 `orjson` 替代标准库**（快 3-5 倍）\n```python\nimport orjson\n\n# 序列化\ndata = orjson.dumps({\"name\": \"test\", \"values\": [1, 2, 3]})\n\n# 反序列化\nobj = orjson.loads(data)\n```\n\n2. **批量处理代替逐条处理**\n```python\n# 慢：逐条序列化\nfor item in large_list:\n    json.dumps(item)\n\n# 快：一次序列化整个列表\njson.dumps(large_list)\n```\n\n3. **缓存重复序列化**\n```python\nfrom functools import lru_cache\n\n@lru_cache(maxsize=256)\ndef user_to_json(user_id, name):\n    return json.dumps({\"id\": user_id, \"name\": name})\n```\n\n4. **使用 Protocol Buffers / MessagePack**（二进制格式，比 JSON 快 5-10 倍）\n```python\nimport msgpack\n\ndata = msgpack.packb({\"name\": \"test\", \"values\": [1, 2, 3]})\nobj = msgpack.unpackb(data)\n```\n\n**选择指南**：\n- 内部服务通信：MessagePack / Protobuf\n- 对外 API：JSON（兼容性好）\n- 高频场景：orjson + 缓存"
    },
    {
        "user": "优化这个 Python pandas 操作：对大数据集进行复杂过滤和聚合",
        "assistant": "**优化策略**：\n\n```python\n# 原代码\ndf = pd.read_csv('large_file.csv')\nfiltered = df[(df['status'] == 'active') & (df['score'] > 80)]\nresult = filtered.groupby('category').agg({'amount': 'sum'})\n```\n\n**优化**：\n\n1. **分块读取**（文件太大无法一次加载）\n```python\nchunks = []\nfor chunk in pd.read_csv('large_file.csv', chunksize=100000):\n    filtered_chunk = chunk[(chunk['status'] == 'active') & (chunk['score'] > 80)]\n    chunks.append(filtered_chunk.groupby('category').agg({'amount': 'sum'}))\nresult = pd.concat(chunks).groupby('category').sum()\n```\n\n2. **指定数据类型减少内存**\n```python\ndf = pd.read_csv('large_file.csv', dtype={\n    'id': 'int32',\n    'status': 'category',  # 枚举→更省内存\n    'score': 'float32',\n    'amount': 'float32',\n})\n```\n\n3. **使用 query 方法**（对大数据集更快）\n```python\nfiltered = df.query('status == \"active\" and score > 80')\n```\n\n4. **使用 Polars 替代 Pandas**（快 5-10 倍，内存更省）\n```python\nimport polars as pl\n\ndf = pl.read_csv('large_file.csv')\nresult = df.filter(\n    (pl.col('status') == 'active') & (pl.col('score') > 80)\n).group_by('category').agg(pl.col('amount').sum())\n```"
    },
    {
        "user": "优化这段生成大量 HTML 的 Python Web 代码",
        "assistant": "**问题**：在 Python 代码中拼接 HTML 字符串难以维护，性能也差。\n\n**优化方案 1：使用模板引擎**\n```python\nfrom jinja2 import Environment, FileSystemLoader\n\nenv = Environment(loader=FileSystemLoader('templates'))\ntemplate = env.get_template('report.html')\nhtml = template.render(items=items, title='Report')\n```\n\n**优化方案 2：使用 HTML 构建器**\n```python\nfrom dominate import tags\n\ndef build_report(items):\n    with tags.div(cls='container') as container:\n        tags.h1('Report')\n        with tags.ul():\n            for item in items:\n                tags.li(tags.a(item.name, href=f'/item/{item.id}'))\n    return container.render()\n```\n\n**优化方案 3：列表 + join 替代字符串拼接**\n```python\ndef build_options(items):\n    parts = [f'<option value=\"{item.id}\">{item.name}</option>' for item in items]\n    return ''.join(parts)\n# 比 for 循环中 += 快 10 倍以上\n```\n\n**原则**：\n- 静态 HTML：模板引擎\n- 动态组件：构建器库\n- 必须手动拼接：用列表收集 + join"
    },
    {
        "user": "如何优化 Redis 的批量操作？",
        "assistant": "**批量优化方案**：\n\n```python\nimport redis\nr = redis.Redis()\n\n# ❌ 慢：逐个操作，N 次网络往返\nfor key, value in data.items():\n    r.set(key, value, ex=3600)\n\n# ✅ 快：Pipeline 批量发送\npipe = r.pipeline()\nfor key, value in data.items():\n    pipe.setex(key, 3600, value)  # setex = SET + EXPIRE\nresults = pipe.execute()\n```\n\n**Pipeline 原理**：\n- 将多个命令打包一次性发送\n- 减少网络往返次数（RTT）\n- 100 条命令 → 从 100 次 RTT 降为 1 次 RTT\n\n**其他批量优化**：\n\n```python\n# MGET/MSET 比 Pipeline 更快（单个命令）\nr.mset({k: v for k, v in data.items()})  # 批量 SET\nvalues = r.mget(keys)  # 批量 GET\n\n# Lua 脚本（原子操作）\nlua_script = \"\"\"\nfor i, key in ipairs(KEYS) do\n    redis.call('SET', key, ARGV[i], 'EX', ARGV[#ARGV])\nend\nreturn 'OK'\n\"\"\"\nr.eval(lua_script, len(keys), *keys, *values, 3600)\n```\n\n**优先级**：MSET/MGET > Pipeline > 逐个操作。"
    },
    {
        "user": "优化这段计算密集型 Python 代码的处理速度",
        "assistant": "**常见优化路径**（按优先级）：\n\n```python\n# 1. 使用 NumPy 向量化（快 10-100 倍）\nimport numpy as np\n\n# ❌ 慢：Python 循环\nresult = []\nfor i in range(len(a)):\n    result.append(a[i] * b[i] + c[i])\n\n# ✅ 快：NumPy 向量化\nresult = a * b + c\n```\n\n```python\n# 2. 使用 Numba JIT 编译（快 10-1000 倍）\nfrom numba import jit\n\n@jit(nopython=True)\ndef compute(arr):\n    result = 0\n    for i in range(len(arr)):\n        result += arr[i] ** 2\n    return result\n```\n\n```python\n# 3. 多进程并行（CPU 密集）\nfrom concurrent.futures import ProcessPoolExecutor\n\ndef process_chunk(chunk):\n    return [heavy_computation(x) for x in chunk]\n\nchunks = np.array_split(data, 8)  # 分 8 块\nwith ProcessPoolExecutor(max_workers=8) as executor:\n    results = list(executor.map(process_chunk, chunks))\n```\n\n**选择指南**：\n- 数值计算：NumPy 向量化\n- 循环中有 if/else：Numba\n- 数据量大 + 独立：多进程\n- GPU 场景：CuPy / PyTorch"
    },
    {
        "user": "优化这个 API 调用的性能：用户信息页面需要调用 4 个微服务获取不同数据",
        "assistant": "**问题**：顺序调用 4 个服务 → 总耗时 = T1 + T2 + T3 + T4。\n\n**优化方案 1：并行调用**\n```python\nimport asyncio\n\nasync def get_user_page(user_id):\n    # 4 个请求同时发出\n    profile, orders, reviews, recommendations = await asyncio.gather(\n        fetch_profile(user_id),\n        fetch_orders(user_id),\n        fetch_reviews(user_id),\n        fetch_recommendations(user_id),\n    )\n    return render_page(profile, orders, reviews, recommendations)\n```\n总耗时 = max(T1, T2, T3, T4) — 而非 sum。\n\n**优化方案 2：Java CompletableFuture**\n```java\nCompletableFuture<Profile> profileFuture =\n    CompletableFuture.supplyAsync(() -> fetchProfile(userId));\nCompletableFuture<List<Order>> ordersFuture =\n    CompletableFuture.supplyAsync(() -> fetchOrders(userId));\nCompletableFuture<List<Review>> reviewsFuture =\n    CompletableFuture.supplyAsync(() -> fetchReviews(userId));\n\n// 等待所有完成\nCompletableFuture.allOf(profileFuture, ordersFuture, reviewsFuture).join();\n\nPage page = renderPage(\n    profileFuture.get(), ordersFuture.get(), reviewsFuture.get()\n);\n```\n\n**优化方案 3：服务端聚合（BFF 模式）**\n- 后端新增聚合接口 `/api/user-page/{id}` 一次性返回所有数据\n- 由 BFF（Backend For Frontend）或 GraphQL Gateway 做聚合\n\n**对比**：顺序 4×200ms=800ms → 并行 ~200ms，提升 4 倍。"
    },
    {
        "user": "优化 Python 中使用正则的文本处理",
        "assistant": "**优化 1：预编译正则（重复使用场景）**\n```python\n# ❌ 每次调用都编译\nfor line in lines:\n    if re.match(r'^\\d{4}-\\d{2}-\\d{2}', line):\n        process(line)\n\n# ✅ 预编译一次\nDATE_PATTERN = re.compile(r'^\\d{4}-\\d{2}-\\d{2}')\nfor line in lines:\n    if DATE_PATTERN.match(line):\n        process(line)\n```\n\n**优化 2：用 str 方法替代简单正则**\n```python\n# ❌ 正则（慢）\nif re.search(r'error', text, re.IGNORECASE):\n    ...\n\n# ✅ str 方法（快 3-5 倍）\nif 'error' in text.lower():\n    ...\n```\n\n**优化 3：避免捕获组（不需要时）**\n```python\n# ❌ 捕获组有额外开销\npattern = re.compile(r'(\\d+)-(\\d+)-(\\d+)')\n\n# ✅ 非捕获组（如果不是需要提取每组）\npattern = re.compile(r'\\d+-\\d+-\\d+')\n\n# ✅ 需要提取时才捕获\npattern = re.compile(r'(\\d{4})-(\\d{2})-(\\d{2})')  # 提取年月日\n```\n\n**性能参考**：str 方法 > 预编译正则 > 未编译正则。"
    },
]

# ========== 技术问答（原有5条 + 新增16条 = 21） ==========
TECH_QA_EXTRA = [
    {
        "user": "什么是 WebSocket？与 HTTP 有什么区别？",
        "assistant": "**WebSocket** 是一种全双工通信协议，客户端和服务器可以互相主动发送消息。\n\n**HTTP vs WebSocket**：\n\n| 特性 | HTTP | WebSocket |\n|------|------|-----------|\n| 通信模式 | 请求-响应 | 全双工 |\n| 谁发起 | 客户端 | 双向 |\n| 连接方式 | 短连接/长连接 | 持久连接 |\n| 开销 | 每次请求带完整头部 | 初始握手后头部极小 |\n| 适用场景 | REST API、网页加载 | 聊天、实时数据、游戏 |\n\n```python\n# Python WebSocket 服务端示例（使用 websockets 库）\nimport asyncio\nimport websockets\n\nasync def handler(websocket):\n    async for message in websocket:\n        await websocket.send(f\"Echo: {message}\")\n\nasync def main():\n    async with websockets.serve(handler, \"localhost\", 8765):\n        await asyncio.Future()  # 永久运行\n\nasyncio.run(main())\n```\n\n**适用场景**：聊天应用、实时通知、协作编辑、股票行情、在线游戏。"
    },
    {
        "user": "Python 中 `is` 和 `==` 的区别是什么？",
        "assistant": "`is` 比较**对象身份**（内存地址），`==` 比较**对象值**（通过 `__eq__` 方法）。\n\n```python\na = [1, 2, 3]\nb = [1, 2, 3]\nc = a\n\nprint(a == b)  # True  — 值相同\nprint(a is b)  # False — 不同对象\nprint(a is c)  # True  — 同一对象\n```\n\n**特例：小整数和短字符串缓存**\n```python\nx = 256\ny = 256\nprint(x is y)  # True（CPython 缓存 -5 ~ 256）\n\nx = 257\ny = 257\nprint(x is y)  # False（超出缓存范围）\n```\n\n**规则**：\n- 与 `None` 比较：始终用 `is None`（唯一单例）\n- 比较值：用 `==`\n- 不要依赖小整数缓存的 `is` 行为"
    },
    {
        "user": "什么是 CI/CD（持续集成/持续部署）？",
        "assistant": "**CI/CD** 是软件开发中的自动化实践：\n\n**CI（持续集成）**：\n- 开发人员频繁合并代码到主分支\n- 自动构建、自动测试\n- 快速发现集成问题\n\n**CD（持续交付/持续部署）**：\n- 持续交付：自动构建 + 测试，手动部署\n- 持续部署：自动构建 + 测试 + 部署（全自动）\n\n**典型 GitHub Actions CI/CD 流程**：\n```yaml\nname: CI/CD Pipeline\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  build-and-test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Setup Python\n        uses: actions/setup-python@v5\n        with:\n          python-version: '3.12'\n      - name: Install dependencies\n        run: pip install -r requirements.txt\n      - name: Run tests\n        run: pytest tests/ -v --cov\n      - name: Lint\n        run: ruff check .\n\n  deploy:\n    needs: build-and-test\n    if: github.ref == 'refs/heads/main'\n    runs-on: ubuntu-latest\n    steps:\n      - name: Deploy to server\n        run: |\n          ssh deploy@server 'cd /app && docker-compose pull && docker-compose up -d'\n```\n\n**好处**：减少人工错误、快速反馈、加速交付。"
    },
    {
        "user": "Python 中的 `*args` 和 `**kwargs` 是什么？",
        "assistant": "`*args` 和 `**kwargs` 用于定义可变参数函数。\n\n**`*args`**：接收任意数量的位置参数，包装为 tuple\n```python\ndef sum_all(*args):\n    return sum(args)\n\nprint(sum_all(1, 2, 3, 4, 5))  # 15\n```\n\n**`**kwargs`**：接收任意数量的关键字参数，包装为 dict\n```python\ndef create_user(**kwargs):\n    print(kwargs)\n\ncreate_user(name=\"张三\", age=25, email=\"test@mail.com\")\n# {'name': '张三', 'age': 25, 'email': 'test@mail.com'}\n```\n\n**组合使用**：\n```python\ndef logger(func):\n    def wrapper(*args, **kwargs):\n        print(f\"调用 {func.__name__}，args={args}，kwargs={kwargs}\")\n        return func(*args, **kwargs)  # 解包传递\n    return wrapper\n```\n\n**在函数调用时解包**：\n```python\nnumbers = [1, 2, 3]\nconfig = {\"mode\": \"fast\", \"debug\": True}\n\nresult = some_func(*numbers, **config)\n# 等价于 some_func(1, 2, 3, mode=\"fast\", debug=True)\n```"
    },
    {
        "user": "Docker 的核心概念是什么？（镜像、容器、Dockerfile）",
        "assistant": "**Docker 三大核心概念**：\n\n**1. 镜像（Image）**\n- 应用的只读模板，包含运行环境和代码\n- 分层存储，每层独立可复用\n- 从 Dockerfile 构建：`docker build -t myapp:v1 .`\n\n**2. 容器（Container）**\n- 镜像的运行实例\n- 轻量级隔离（共享内核，独立文件系统/进程/网络）\n- `docker run -d -p 8080:8080 --name app myapp:v1`\n\n**3. Dockerfile**\n- 定义镜像构建步骤的文本文件\n```dockerfile\nFROM python:3.12-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nEXPOSE 8000\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n```\n\n**与虚拟机的区别**：\n| 特性 | Docker | 虚拟机 |\n|------|--------|--------|\n| 启动速度 | 秒级 | 分钟级 |\n| 资源消耗 | MB 级 | GB 级 |\n| 隔离级别 | 进程级 | 硬件级 |\n| 磁盘占用 | 几百 MB | 几 GB |"
    },
    {
        "user": "什么是数据库索引？什么时候使用索引？",
        "assistant": "**索引**是一种数据结构，用于加速数据库的查询操作。\n\n**原理**（B+树索引）：\n- 类似书的目录\n- 查询时先查索引找到位置，再读取数据\n- 避免全表扫描\n\n**何时创建索引**：\n```sql\n-- 1. WHERE 条件列\nCREATE INDEX idx_orders_status ON orders(status);\n\n-- 2. JOIN 的关联列\nCREATE INDEX idx_orders_user_id ON orders(user_id);\n\n-- 3. ORDER BY / GROUP BY 列\nCREATE INDEX idx_orders_created ON orders(created_at);\n\n-- 4. 复合索引（覆盖多列）\nCREATE INDEX idx_orders_user_status ON orders(user_id, status);\n-- 满足: WHERE user_id = ? AND status = ?\n-- 也满足: WHERE user_id = ?（最左前缀原则）\n```\n\n**索引的代价**：\n- 占用磁盘空间\n- INSERT/UPDATE/DELETE 变慢（需要更新索引）\n\n**不建议建索引的情况**：\n- 表很小（< 1000 行）\n- 区分度低的列（如性别、布尔值）\n- 频繁更新的列\n- 很少出现在查询中的列\n\n**验证**：用 `EXPLAIN SELECT ...` 查看是否使用了索引。"
    },
    {
        "user": "什么是 Cookie、Session、Token 认证的区别？",
        "assistant": "**三种 Web 认证机制**：\n\n| 机制 | 存储位置 | 扩展性 | 适用场景 |\n|------|---------|--------|---------|\n| Cookie | 浏览器 | 同域 | 传统 Web |\n| Session | 服务端 | 需共享 | 单体应用 |\n| Token (JWT) | 客户端 | 无状态 | 微服务/SPA/App |\n\n**Cookie**：\n- 浏览器自动携带\n- 受同源策略限制\n- 可设置 HttpOnly（防 XSS）、Secure（仅 HTTPS）\n\n**Session**：\n```\n用户登录 → 服务端创建 Session → 返回 SessionID Cookie → 后续请求验证 SessionID\n```\n- Session 数据存在服务端（内存/Redis）\n- 分布式需要 Session 共享\n\n**Token（JWT）**：\n```\n用户登录 → 服务端签发 JWT → 客户端存储 → 每次请求带 Authorization: Bearer <token>\n```\n- 服务端不需要存储\n- 适合微服务和移动端\n- Payload 是明文 Base64（不加密！敏感数据放服务端）\n\n**选择**：传统 Web（Cookie+Session）、SPA（JWT）、微服务（JWT+OAuth2）、高安全（双 Token：Access + Refresh）。"
    },
    {
        "user": "什么是面向对象编程（OOP）的四大特性？",
        "assistant": "**OOP 四大特性**：\n\n**1. 封装（Encapsulation）**\n- 隐藏内部实现，只暴露必要接口\n- 通过 private/protected 控制访问\n```python\nclass BankAccount:\n    def __init__(self):\n        self._balance = 0  # protected\n\n    def deposit(self, amount):\n        if amount > 0:\n            self._balance += amount\n\n    @property\n    def balance(self):\n        return self._balance\n```\n\n**2. 继承（Inheritance）**\n- 子类继承父类的属性和方法\n- 实现代码复用\n\n**3. 多态（Polymorphism）**\n- 同一接口，不同实现\n- 运行时动态绑定\n```python\nclass Dog:\n    def speak(self): return \"Woof!\"\n\nclass Cat:\n    def speak(self): return \"Meow!\"\n\nanimals = [Dog(), Cat()]\nfor a in animals:\n    print(a.speak())  # 调用各自的 speak\n```\n\n**4. 抽象（Abstraction）**\n- 定义接口而不实现细节\n- ABC（Abstract Base Class）\n\n**现代观点**：组合优于继承。不要为了复用而继承，优先使用组合。"
    },
    {
        "user": "什么是 SOLID 原则？",
        "assistant": "**SOLID** 是面向对象设计的五个原则：\n\n**S — 单一职责（Single Responsibility）**\n- 一个类只负责一件事\n```python\n# ❌ 违反：既处理数据又发邮件\nclass OrderProcessor:\n    def process(self, order):\n        self._validate(order)\n        self._save(order)\n        self._send_email(order)  # 邮件逻辑应该分离\n\n# ✅ 符合：拆分职责\nclass OrderProcessor:\n    def process(self, order):\n        self._validate(order)\n        self._save(order)\n        event_bus.publish('order.created', order)\n```\n\n**O — 开闭原则（Open/Closed）**\n- 对扩展开放，对修改关闭\n\n**L — 里氏替换（Liskov Substitution）**\n- 子类可以完全替换父类\n\n**I — 接口隔离（Interface Segregation）**\n- 不强迫客户端依赖不需要的方法\n\n**D — 依赖倒置（Dependency Inversion）**\n- 依赖抽象而非具体实现\n```python\n# ❌ 依赖具体实现\nclass ReportService:\n    def __init__(self):\n        self.db = MySQLDatabase()  # 紧耦合\n\n# ✅ 依赖抽象\nclass ReportService:\n    def __init__(self, db: Database):  # 注入接口\n        self.db = db\n```"
    },
    {
        "user": "什么是测试驱动开发（TDD）？",
        "assistant": "**TDD（Test-Driven Development）** 是一种开发方法：先写测试，再写代码。\n\n**三步循环（Red-Green-Refactor）**：\n\n1. **Red**：写一个失败的测试\n2. **Green**：写最少的代码让测试通过\n3. **Refactor**：重构代码，保持测试通过\n\n**示例**（计算器功能）：\n```python\n# 1. Red：先写测试（此时 add 函数不存在→失败）\ndef test_add():\n    assert add(2, 3) == 5\n    assert add(-1, 1) == 0\n\n# 2. Green：写最简实现\ndef add(a, b):\n    return a + b\n\n# 3. Refactor：如果需要处理更多场景\n# 再加测试 → 再改代码 → 再重构\n```\n\n**好处**：\n- 强制思考需求（测试 = 可执行的需求文档）\n- 减少 Bug（每个功能都有测试覆盖）\n- 重构有安全网（测试通过 = 行为不变）\n- 更好的设计（可测试的代码通常是低耦合的）\n\n**TDD 不是银弹**：探索性开发、UI 原型不适合 TDD。"
    },
    {
        "user": "Python 中 `@staticmethod` 和 `@classmethod` 的区别",
        "assistant": "| 特性 | @staticmethod | @classmethod | 普通方法 |\n|------|--------------|-------------|---------|\n| 第一个参数 | 无特殊参数 | cls（类） | self（实例） |\n| 访问类属性 | 通过类名 | 通过 cls | 通过 self.__class__ |\n| 访问实例属性 | ❌ | ❌ | ✅ |\n| 可被子类覆盖 | ❌ | ✅ | ✅ |\n\n```python\nclass MyClass:\n    class_var = \"类变量\"\n\n    def instance_method(self):\n        return f\"实例方法，访问 {self.class_var}\"\n\n    @classmethod\n    def class_method(cls):\n        return f\"类方法，访问 {cls.class_var}\"\n\n    @staticmethod\n    def static_method():\n        return \"静态方法，不需要类或实例\"\n\n# 使用\nobj = MyClass()\nobj.instance_method()    # 实例方法\nMyClass.class_method()   # 类方法\nMyClass.static_method()  # 静态方法\n```\n\n**使用场景**：\n- `@classmethod`：工厂方法（如 `User.from_json(data)`）、需要子类化\n- `@staticmethod`：工具函数（与类逻辑相关但不需要访问类/实例）"
    },
    {
        "user": "什么是微服务架构？优缺点是什么？",
        "assistant": "**微服务**是一种架构风格，将应用拆分为多个小型、独立的服务。\n\n**核心特征**：\n- 每个服务有自己的数据库、独立的部署周期\n- 服务间通过 API（HTTP/gRPC/消息队列）通信\n- 独立开发、测试、部署、扩展\n\n**优点**：\n- ✅ 独立部署：改订单服务不需要部署用户服务\n- ✅ 独立扩展：只扩展瓶颈服务\n- ✅ 技术异构：不同服务用不同语言/数据库\n- ✅ 故障隔离：一个服务崩溃不影响其他\n- ✅ 团队自治：小团队端到端负责自己的服务\n\n**缺点**：\n- ❌ 分布式复杂度：网络延迟、分布式事务、数据一致性\n- ❌ 运维成本高：需要容器编排、服务发现、监控\n- ❌ 调试困难：跨服务追踪需要分布式链路追踪\n- ❌ 数据一致性：需要 Saga、最终一致性等方案\n\n**何时用**：大型团队 + 复杂业务。小型项目/早期项目用单体更高效。"
    },
    {
        "user": "什么是 Git Flow 分支策略？",
        "assistant": "**Git Flow** 是一种经典的分支管理模型：\n\n```\nmain ─────●────────────●───────● (版本发布)\n           \\          / \\     /\ndevelop ────●──●──●──●───●───●──● (开发主线)\n                 \\    /\nfeature/login ────●──● (功能分支)\n                     \\\nhotfix/bug-123 ───────● (热修复)\n```\n\n**分支类型**：\n\n| 分支 | 来源 | 合并到 | 说明 |\n|------|------|--------|------|\n| main | - | - | 生产代码 |\n| develop | main | main | 开发主线 |\n| feature/* | develop | develop | 新功能开发 |\n| release/* | develop | main + develop | 发布准备 |\n| hotfix/* | main | main + develop | 紧急修复 |\n\n**简化替代方案**：\n\n**GitHub Flow**（推荐小团队）：\n- main + feature 分支\n- feature → PR → 合并到 main → 自动部署\n\n**GitLab Flow**：\n- main + 环境分支（staging/production）\n\n**原则**：分支策略越复杂，管理成本越高。选择合适的复杂度。"
    },
    {
        "user": "Python 的 `try-except-else-finally` 执行顺序是怎样的？",
        "assistant": "**执行流程**：\n\n```python\ntry:\n    # 1. 首先执行，如果无异常\n    result = risky_operation()\nexcept ValueError:\n    # 2. try 中发生 ValueError 时执行\n    print(\"捕获 ValueError\")\nexcept Exception:\n    # 3. 发生其他异常时执行\n    print(\"捕获其他异常\")\nelse:\n    # 4. try 成功（无异常）后执行\n    print(f\"成功，结果: {result}\")\nfinally:\n    # 5. 无论如何都会执行\n    close_resources()\n```\n\n**各子句的作用**：\n- `try`：可能抛出异常的代码\n- `except`：捕获并处理特定异常\n- `else`：try 成功时才执行（与放在 try 末尾的区别：明确排除异常路径）\n- `finally`：清理资源（即使 return/break/continue 也会执行）\n\n```python\ndef demo():\n    try:\n        return \"try\"\n    finally:\n        print(\"finally 先执行\")  # 先打印这个！\n    return \"不会执行到\"\n\n# 输出：\n# finally 先执行\n# 返回 \"try\"\n```\n\n**最佳实践**：资源清理用 `with`，复杂清理逻辑用 `finally`。"
    },
    {
        "user": "什么是 CAP 定理？在分布式系统中如何权衡？",
        "assistant": "**CAP 定理**指出，分布式系统最多只能同时满足三个中的两个：\n\n- **C（Consistency，一致性）**：所有节点在同一时刻看到相同数据\n- **A（Availability，可用性）**：每个请求都得到非错误的响应\n- **P（Partition Tolerance，分区容错性）**：网络分区时系统继续运行\n\n```\n        C\n       / \\\n      /   \\\n     /     \\\n    A-------P\n```\n\n**实际选择**（P 在分布式系统中无法避免，所以是 CP vs AP）：\n\n**CP（一致 + 分区容错）**：\n- 网络分区时牺牲可用性\n- 例：ZooKeeper、etcd、银行转账\n- 主节点故障时暂停服务直到选出新主\n\n**AP（可用 + 分区容错）**：\n- 网络分区时牺牲强一致性\n- 例：DNS、Cassandra、社交媒体\n- 允许短暂的数据不一致，最终一致\n\n**BASE 理论**（AP 的实践）：\n- Basically Available（基本可用）\n- Soft state（软状态）\n- Eventually consistent（最终一致性）\n\n**注意**：CAP 的 C 是强一致性（线性一致性）。现代系统常使用最终一致性模型。"
    },
    {
        "user": "Python 的 Garbage Collection（垃圾回收）是如何工作的？",
        "assistant": "CPython 使用**引用计数**为主 + **分代回收**为辅的 GC 机制。\n\n**1. 引用计数（主）**：\n```python\nimport sys\n\na = []\nb = a\nprint(sys.getrefcount(a))  # 3（a, b, getrefcount 参数）\n\ndel b\nprint(sys.getrefcount(a))  # 2\n```\n- 每个对象维护一个引用计数\n- 计数归零 → 立即释放内存\n- 优点：实时、简单\n- 缺点：无法处理循环引用\n\n**2. 分代回收（循环引用处理）**：\n```python\n# 循环引用（引用计数无法处理）\nclass Node:\n    def __init__(self):\n        self.ref = None\n\na = Node()\nb = Node()\na.ref = b\nb.ref = a  # 循环引用！\ndel a, b   # 引用计数不为 0，需 GC 检测\n```\n\nGC 分三代：\n- Gen 0：新对象，回收最频繁\n- Gen 1：存活过一次 GC 的对象\n- Gen 2：长期存活的对象，回收最少\n\n**控制 GC**：\n```python\nimport gc\ngc.collect()       # 强制回收\ngc.disable()       # 禁用（性能关键场景）\ngc.set_threshold(700, 10, 10)  # 调整阈值\n```"
    },
]

# ========== 文档模板（原有2条 + 新增14条 = 16） ==========
README_TEMPLATES_EXTRA = [
    {
        "user": "写一个 .gitignore 模板（Python 项目）",
        "assistant": "```gitignore\n# Python\n__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.Python\n*.egg-info/\ndist/\nbuild/\n*.egg\n\n# 虚拟环境\nvenv/\n.venv/\nenv/\nENV/\n\n# IDE\n.vscode/\n.idea/\n*.swp\n*.swo\n*~\n\n# 环境配置\n.env\n.env.local\n.env.*.local\n\n# 日志\n*.log\nlogs/\n\n# 数据库\n*.db\n*.sqlite\n*.sqlite3\n\n# 操作系统\n.DS_Store\nThumbs.db\n\n# Jupyter\n.ipynb_checkpoints/\n\n# 测试\n.pytest_cache/\n.coverage\nhtmlcov/\n```"
    },
    {
        "user": "写一个 Makefile 模板（Python 项目）",
        "assistant": "```makefile\n.PHONY: help install test lint format clean run\n\nhelp:  ## 显示帮助信息\n\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \\\n\t\tawk 'BEGIN {FS = \":.*?## \"}; {printf \"\\033[36m%-15s\\033[0m %s\\n\", $$1, $$2}'\n\ninstall:  ## 安装依赖\n\tpip install -r requirements.txt\n\tpip install -r requirements-dev.txt\n\ntest:  ## 运行测试\n\tpytest tests/ -v --cov=src --cov-report=html\n\nlint:  ## 代码检查\n\truff check src/ tests/\n\tmypy src/\n\nformat:  ## 代码格式化\n\truff format src/ tests/\n\truff check --fix src/ tests/\n\nclean:  ## 清理临时文件\n\tfind . -type d -name \"__pycache__\" -exec rm -rf {} + 2>/dev/null || true\n\tfind . -type d -name \".pytest_cache\" -exec rm -rf {} + 2>/dev/null || true\n\trm -rf build/ dist/ *.egg-info htmlcov/ .coverage\n\nrun:  ## 启动开发服务器\n\tpython -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000\n\nbuild:  ## 构建 Docker 镜像\n\tdocker build -t myapp:latest .\n```"
    },
    {
        "user": "写一个 Docker Compose 模板（Python + MySQL + Redis）",
        "assistant": "```yaml\nversion: '3.8'\n\nservices:\n  app:\n    build:\n      context: .\n      dockerfile: Dockerfile\n    container_name: myapp\n    ports:\n      - \"8000:8000\"\n    environment:\n      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/mydb\n      - REDIS_URL=redis://redis:6379/0\n    depends_on:\n      mysql:\n        condition: service_healthy\n      redis:\n        condition: service_healthy\n    volumes:\n      - ./logs:/app/logs\n    restart: unless-stopped\n\n  mysql:\n    image: mysql:8.0\n    container_name: mysql\n    environment:\n      MYSQL_ROOT_PASSWORD: root_password\n      MYSQL_DATABASE: mydb\n      MYSQL_USER: user\n      MYSQL_PASSWORD: password\n    ports:\n      - \"3306:3306\"\n    volumes:\n      - mysql_data:/var/lib/mysql\n    healthcheck:\n      test: [\"CMD\", \"mysqladmin\", \"ping\", \"-h\", \"localhost\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n    restart: unless-stopped\n\n  redis:\n    image: redis:7-alpine\n    container_name: redis\n    ports:\n      - \"6379:6379\"\n    volumes:\n      - redis_data:/data\n    healthcheck:\n      test: [\"CMD\", \"redis-cli\", \"ping\"]\n      interval: 10s\n      timeout: 5s\n      retries: 5\n    restart: unless-stopped\n\nvolumes:\n  mysql_data:\n  redis_data:\n```"
    },
    {
        "user": "写一个 GitHub Actions CI 配置模板（Python 项目）",
        "assistant": "```yaml\nname: CI\n\non:\n  push:\n    branches: [main, develop]\n  pull_request:\n    branches: [main]\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    strategy:\n      matrix:\n        python-version: ['3.10', '3.11', '3.12']\n\n    steps:\n      - uses: actions/checkout@v4\n\n      - name: Set up Python ${{ matrix.python-version }}\n        uses: actions/setup-python@v5\n        with:\n          python-version: ${{ matrix.python-version }}\n          cache: 'pip'\n\n      - name: Install dependencies\n        run: |\n          python -m pip install --upgrade pip\n          pip install -r requirements.txt\n          pip install -r requirements-dev.txt\n\n      - name: Lint with ruff\n        run: ruff check .\n\n      - name: Type check with mypy\n        run: mypy src/ --ignore-missing-imports\n\n      - name: Test with pytest\n        run: pytest tests/ -v --cov=src --cov-report=xml\n\n      - name: Upload coverage to Codecov\n        uses: codecov/codecov-action@v4\n        with:\n          file: ./coverage.xml\n          fail_ci_if_error: false\n\n  build:\n    needs: test\n    runs-on: ubuntu-latest\n    if: github.ref == 'refs/heads/main'\n    steps:\n      - uses: actions/checkout@v4\n      - name: Build Docker image\n        run: docker build -t myapp:${{ github.sha }} .\n```"
    },
    {
        "user": "写一个 Nginx 反向代理配置模板",
        "assistant": "```nginx\nserver {\n    listen 80;\n    server_name example.com;\n    return 301 https://$host$request_uri;  # 强制 HTTPS\n}\n\nserver {\n    listen 443 ssl http2;\n    server_name example.com;\n\n    # SSL 证书\n    ssl_certificate     /etc/nginx/ssl/example.com.crt;\n    ssl_certificate_key /etc/nginx/ssl/example.com.key;\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_ciphers HIGH:!aNULL:!MD5;\n\n    # 日志\n    access_log /var/log/nginx/example_access.log;\n    error_log  /var/log/nginx/example_error.log;\n\n    # 静态文件\n    location /static/ {\n        alias /var/www/static/;\n        expires 30d;\n        add_header Cache-Control \"public, immutable\";\n    }\n\n    # API 反向代理\n    location /api/ {\n        proxy_pass http://backend:8080/api/;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n        proxy_read_timeout 60s;\n        proxy_connect_timeout 5s;\n    }\n\n    # 前端 SPA\n    location / {\n        root /var/www/frontend;\n        try_files $uri $uri/ /index.html;\n    }\n\n    # 安全头\n    add_header X-Frame-Options \"SAMEORIGIN\" always;\n    add_header X-Content-Type-Options \"nosniff\" always;\n    add_header X-XSS-Protection \"1; mode=block\" always;\n\n    # 限制请求速率\n    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;\n    location /api/ {\n        limit_req zone=api_limit burst=20 nodelay;\n    }\n}\n```"
    },
    {
        "user": "写一个 systemd 服务文件模板",
        "assistant": "```ini\n[Unit]\nDescription=我的 Python Web 应用\nAfter=network.target mysql.service redis.service\nWants=mysql.service redis.service\n\n[Service]\nType=simple\nUser=app\nGroup=app\nWorkingDirectory=/opt/myapp\nEnvironmentFile=/opt/myapp/.env\nExecStart=/opt/myapp/venv/bin/python -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --workers 4\nExecReload=/bin/kill -HUP $MAINPID\nRestart=always\nRestartSec=10\nStandardOutput=append:/var/log/myapp/stdout.log\nStandardError=append:/var/log/myapp/stderr.log\n\n# 安全加固\nNoNewPrivileges=yes\nPrivateTmp=yes\nProtectSystem=strict\nReadWritePaths=/opt/myapp/logs /opt/myapp/uploads\nProtectHome=yes\n\n# 资源限制\nMemoryMax=512M\nCPUQuota=200%\n\n[Install]\nWantedBy=multi-user.target\n```\n\n使用方法：\n```bash\nsudo cp myapp.service /etc/systemd/system/\nsudo systemctl daemon-reload\nsudo systemctl enable --now myapp\nsudo systemctl status myapp\n```"
    },
    {
        "user": "写一个 VS Code 的 Python 项目配置模板",
        "assistant": "```json\n// .vscode/settings.json\n{\n    \"python.defaultInterpreterPath\": \"${workspaceFolder}/venv/bin/python\",\n    \"python.linting.enabled\": true,\n    \"python.linting.pylintEnabled\": false,\n    \"python.linting.ruffEnabled\": true,\n    \"python.formatting.provider\": \"none\",\n    \"[python]\": {\n        \"editor.formatOnSave\": true,\n        \"editor.defaultFormatter\": \"charliermarsh.ruff\",\n        \"editor.codeActionsOnSave\": {\n            \"source.organizeImports\": \"explicit\",\n            \"source.fixAll\": \"explicit\"\n        }\n    },\n    \"python.testing.pytestEnabled\": true,\n    \"python.testing.pytestArgs\": [\"tests\", \"-v\"],\n    \"python.testing.autoTestDiscoverOnSaveEnabled\": true,\n    \"files.exclude\": {\n        \"**/__pycache__\": true,\n        \"**/*.pyc\": true,\n        \".pytest_cache\": true,\n        \".coverage\": true,\n        \"htmlcov\": true\n    },\n    \"files.watcherExclude\": {\n        \"**/venv/**\": true,\n        \"**/node_modules/**\": true\n    }\n}\n```\n\n```json\n// .vscode/launch.json\n{\n    \"version\": \"0.2.0\",\n    \"configurations\": [\n        {\n            \"name\": \"Python: FastAPI\",\n            \"type\": \"debugpy\",\n            \"request\": \"launch\",\n            \"module\": \"uvicorn\",\n            \"args\": [\"src.main:app\", \"--reload\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"],\n            \"jinja\": true,\n            \"env\": {\"PYTHONPATH\": \"${workspaceFolder}\"}\n        },\n        {\n            \"name\": \"Python: 当前文件\",\n            \"type\": \"debugpy\",\n            \"request\": \"launch\",\n            \"program\": \"${file}\",\n            \"console\": \"integratedTerminal\"\n        },\n        {\n            \"name\": \"Pytest: 当前测试\",\n            \"type\": \"debugpy\",\n            \"request\": \"launch\",\n            \"module\": \"pytest\",\n            \"args\": [\"${file}\", \"-v\", \"-s\"]\n        }\n    ]\n}\n```"
    },
    {
        "user": "写一个 Python 日志配置模板",
        "assistant": "```python\nimport logging\nimport logging.config\nfrom pathlib import Path\n\nLOGGING_CONFIG = {\n    'version': 1,\n    'disable_existing_loggers': False,\n    'formatters': {\n        'default': {\n            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)d] %(message)s',\n            'datefmt': '%Y-%m-%d %H:%M:%S',\n        },\n        'simple': {\n            'format': '%(levelname)s: %(message)s',\n        },\n        'json': {\n            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',\n            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',\n        },\n    },\n    'handlers': {\n        'console': {\n            'class': 'logging.StreamHandler',\n            'level': 'DEBUG',\n            'formatter': 'simple',\n            'stream': 'ext://sys.stdout',\n        },\n        'file': {\n            'class': 'logging.handlers.RotatingFileHandler',\n            'level': 'INFO',\n            'formatter': 'default',\n            'filename': 'logs/app.log',\n            'maxBytes': 10485760,  # 10MB\n            'backupCount': 10,\n            'encoding': 'utf-8',\n        },\n        'error_file': {\n            'class': 'logging.handlers.RotatingFileHandler',\n            'level': 'ERROR',\n            'formatter': 'default',\n            'filename': 'logs/error.log',\n            'maxBytes': 10485760,\n            'backupCount': 5,\n            'encoding': 'utf-8',\n        },\n    },\n    'root': {\n        'level': 'INFO',\n        'handlers': ['console', 'file', 'error_file'],\n    },\n    'loggers': {\n        'myapp': {\n            'level': 'DEBUG',\n            'handlers': ['console', 'file'],\n            'propagate': False,\n        },\n        'sqlalchemy.engine': {\n            'level': 'WARNING',  # 减少 SQL 日志\n            'handlers': ['console'],\n            'propagate': False,\n        },\n    },\n}\n\n# 初始化\nPath('logs').mkdir(exist_ok=True)\nlogging.config.dictConfig(LOGGING_CONFIG)\nlogger = logging.getLogger(__name__)\n```"
    },
    {
        "user": "写一个 Python 项目的目录结构模板",
        "assistant": "```\nmyproject/\n├── src/                     # 源代码\n│   ├── __init__.py\n│   ├── main.py              # 入口文件\n│   ├── config.py            # 配置管理\n│   ├── models/              # 数据模型\n│   │   ├── __init__.py\n│   │   └── user.py\n│   ├── services/            # 业务逻辑\n│   │   ├── __init__.py\n│   │   └── user_service.py\n│   ├── api/                 # API 路由\n│   │   ├── __init__.py\n│   │   └── routes/\n│   │       ├── __init__.py\n│   │       └── users.py\n│   ├── db/                  # 数据库\n│   │   ├── __init__.py\n│   │   ├── session.py       # 连接管理\n│   │   └── migrations/      # 数据库迁移\n│   └── utils/               # 工具函数\n│       ├── __init__.py\n│       └── helpers.py\n├── tests/                   # 测试\n│   ├── __init__.py\n│   ├── conftest.py          # pytest fixtures\n│   ├── test_models/\n│   ├── test_services/\n│   └── test_api/\n├── config/                  # 配置文件\n│   ├── settings.yaml\n│   └── logging.yaml\n├── scripts/                 # 脚本工具\n│   ├── seed_db.py\n│   └── migrate.py\n├── docs/                    # 文档\n│   └── api.md\n├── Dockerfile\n├── docker-compose.yml\n├── Makefile\n├── pyproject.toml           # 项目元数据和工具配置\n├── requirements.txt         # 生产依赖\n├── requirements-dev.txt     # 开发依赖\n├── .env.example             # 环境变量模板\n├── .gitignore\n└── README.md\n```"
    },
    {
        "user": "写一个 REST API 接口文档模板",
        "assistant": "## API 接口文档\n\n### 基础信息\n\n- 基础 URL：`https://api.example.com/v1`\n- 认证方式：Bearer Token（Header: `Authorization: Bearer <token>`）\n- 请求格式：`application/json`（POST/PUT/PATCH）\n- 响应格式：`application/json`\n\n### 通用响应格式\n\n```json\n{\n  \"code\": 0,\n  \"message\": \"success\",\n  \"data\": { ... },\n  \"request_id\": \"req_abc123\"\n}\n```\n\n### 错误码\n\n| Code | HTTP Status | 说明 |\n|------|-------------|------|\n| 0 | 200 | 成功 |\n| 1001 | 400 | 参数错误 |\n| 1002 | 401 | 未认证 |\n| 1003 | 403 | 无权限 |\n| 1004 | 404 | 资源不存在 |\n| 2001 | 500 | 服务器内部错误 |\n\n### 接口列表\n\n#### 1. 用户列表\n\n```\nGET /api/v1/users\n```\n\n**查询参数**：\n\n| 参数 | 类型 | 必填 | 默认值 | 说明 |\n|------|------|------|--------|------|\n| page | int | 否 | 1 | 页码 |\n| page_size | int | 否 | 20 | 每页大小（最大100） |\n| status | string | 否 | - | 状态筛选：active/inactive |\n\n**成功响应 (200)**：\n```json\n{\n  \"code\": 0,\n  \"data\": {\n    \"items\": [\n      {\n        \"id\": 1,\n        \"username\": \"zhangsan\",\n        \"email\": \"zhangsan@example.com\",\n        \"status\": \"active\",\n        \"created_at\": \"2024-01-01T00:00:00Z\"\n      }\n    ],\n    \"total\": 100,\n    \"page\": 1,\n    \"page_size\": 20\n  }\n}\n```\n\n#### 2. 创建用户\n\n```\nPOST /api/v1/users\n```\n\n**请求体**：\n```json\n{\n  \"username\": \"zhangsan\",\n  \"email\": \"zhangsan@example.com\",\n  \"password\": \"secure_password\"\n}\n```\n\n**成功响应 (201)**：\n```json\n{\n  \"code\": 0,\n  \"data\": { \"id\": 1, \"username\": \"zhangsan\" }\n}\n```"
    },
]

# ========== 合并函数 ==========
def get_extra_data():
    """返回补充数据的列表，格式与 build_sft_data() 一致"""
    data = []
    categories = [
        ("代码生成", CODE_GENERATION_EXTRA),
        ("代码解释", CODE_EXPLANATION_EXTRA),
        ("Bug修复", BUG_FIX_EXTRA),
        ("代码优化", CODE_OPTIMIZATION_EXTRA),
        ("技术问答", TECH_QA_EXTRA),
        ("文档模板", README_TEMPLATES_EXTRA),
    ]
    for cat_name, items in categories:
        for item in items:
            data.append({
                "messages": [
                    {"role": "user", "content": item["user"]},
                    {"role": "assistant", "content": item["assistant"]},
                ],
                "category": cat_name,
            })
    return data
